Repository glific/glific, pull requests merged in 2021-11, with the labels that each got.

#1860 Stripe fixes for handling cancelled subscription
  lib/glific/partners/invoice.ex
Labels: production-bug, Priority : Low

#1858 Stir report flow
  lib/glific/clients/stir.ex
Labels: enhancement, consulting

#1859 Create extenstion for lahi
  lib/glific/clients/lahi.ex
Labels: consulting

#1881 Interactive msg optional title
  api.docs/includes/_interactive.md
  lib/glific/flows/contact_action.ex
  lib/glific/messages.ex
  lib/glific/templates/interactive_template.ex
  lib/glific/templates/interactive_templates.ex
  lib/glific_web/schema/interactive_template_types.ex
  priv/repo/migrations/20211124063048_interactive_msg_optional_title.exs
  test/glific/messages_test.exs
Labels: enhancement

#1879 Feature/live view
  coveralls.json
  lib/glific/communications/message.ex
  lib/glific/flows/flow_context.ex
  lib/glific/flows/node.ex
  lib/glific_web.ex
  lib/glific_web/router.ex
  lib/glific_web/telemetry.ex
  lib/glific_web/templates/live/stats_live.ex
Labels: enhancement

#1886 Feature/import contacts
  api.docs/includes/_import.md
  assets/gql/contacts/import.gql
  lib/glific/enums/constants/enums.ex
  lib/glific/enums/ecto_enums.ex
  lib/glific/enums/enums.ex
  lib/glific/groups.ex
  lib/glific/templates/interactive_templates.ex
  lib/glific_web/resolvers/contacts.ex
  lib/glific_web/schema/contact_types.ex
  lib/glific_web/schema/enum_types.ex
  priv/repo/migrations/20211129114942_import_contact_type.exs
  test/glific/messages_test.exs
  test/glific_web/schema/contact_test.exs
Labels: enhancement

#1888 Feature/fetch groups
  api.docs/includes/_groups.md
  assets/gql/groups/organization_list.gql
  lib/glific/groups.ex
  lib/glific_web/resolvers/groups.ex
  lib/glific_web/schema/group_types.ex
  test/glific_web/schema/group_test.exs
Labels: enhancement
