Repository glific/glific, pull requests merged in 2021-12, with the labels that each got.

#1891 removing skip message
  lib/glific/processor/consumer_flow.ex
Labels: production-bug

#1897 added previous month video support
  lib/glific/clients/stir.ex
Labels: consulting

#1900 added check for validating billing in webhook
  lib/glific/partners/invoice.ex
  test/glific/partners/invoice_test.exs
Labels: production-bug

#1906 Avanti classes nudge
  lib/glific/clients/avanti.ex
Labels: consulting

#1909 Templates: translated button templates parsing
  lib/glific/messages.ex
  lib/glific/seeds/seeds_dev.ex
  test/glific/messages_test.exs
Labels: production-bug, Priority : Low

#1912 Hiding blocked contacts from chat screen
  lib/glific/searches.ex
Labels: production-bug

#1925 Import Contact: Optin time fixes
  lib/glific/contacts/import.ex
  test/glific/contacts_test.exs
  test/glific_web/schema/contact_test.exs
Labels: bug

#1920 Feature/button template with variable
  lib/glific/messages.ex
  lib/glific/providers/gupshup/template.ex
  lib/glific/templates.ex
  test/glific/templates_test.exs
Labels: enhancement

#1923 updating schema and queue table
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: enhancement

#1929 Feature/new contact flow
  api.docs/includes/_organizations.md
  lib/glific/flows.ex
  lib/glific/partners/organization.ex
  lib/glific/processor/consumer_flow.ex
  lib/glific/seeds/seeds_migration.ex
  lib/glific_web/schema/organization_types.ex
  priv/repo/migrations/20211222095004_organization_newcontact_flow_id.exs
  priv/repo/seeds/20200723172939_add_glific_data.exs
  test/glific/partners/partners_test.exs
Labels: enhancement

#1930 Change the inactive reminder day - STIR
  lib/glific/clients/stir.ex
Labels: consulting

#1941 Consulting Hour: Fixes while updating
  lib/glific_web/resolvers/consulting_hours.ex
  test/glific_web/schema/consulting_hour_test.exs
Labels: production-bug

#1932 Feature/translated template variable
  lib/glific/flows/action.ex
  lib/glific/flows/contact_action.ex
  lib/glific/flows/node.ex
  lib/glific/flows/templating.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific/seeds/seeds_flows.ex
  priv/data/flows/template.json
  test/glific/flows_test.exs
  test/glific/state_test.exs
Labels: enhancement

#1944 Memory optimizations in node
  lib/glific/clients/nayi_disha/data.ex
  lib/glific/flows.ex
  lib/glific/flows/action.ex
  lib/glific/flows/contact_action.ex
  lib/glific/flows/localization.ex
  lib/glific/flows/node.ex
  lib/glific/seeds/seeds_migration.ex
  lib/glific_web/resolvers/consulting_hours.ex
  priv/data/flows/template.json
  test/glific/contacts_test.exs
  test/glific_web/schema/contact_test.exs
Labels: production-bug

#1946 Bug/Trigger: frequency with `does not repeat`
  lib/glific/triggers/trigger.ex
  test/glific/triggers_test.exs
Labels: production-bug

#1947 WebhookLogs: added phone as filter
  lib/glific/flows/webhook_log.ex
  lib/glific_web/schema/webhook_log_types.ex
  test/glific/flows/webhook_test.exs
Labels: enhancement
