Repository glific/glific, pull requests merged in 2022-07, with the labels that each got.

#2336 School id changes
  lib/glific/clients/kef.ex
Labels: ready for review

#2338 KEF - userinput school id match
  lib/glific/clients/kef.ex
Labels: ready for review, consulting

#2344 Hotfix: updating VCR with monthly user usage testcase
  test/glific/partners/billing_test.exs
  test/support/ex_vcr/update_monthly_usage.json
Labels: Testcase
