Repository glific/glific, pull requests merged in 2022-03, with the labels that each got.

#2101 Mukkamaar: Nudges
  lib/glific/clients.ex
  lib/glific/clients/mukkamaar.ex
Labels: consulting

#2104 Webhook/mukkamaar nudges
  lib/glific/clients/mukkamaar.ex
Labels: consulting

#2107 Added single interactive message api for floweditor
  lib/glific_web/flows/flow_editor_controller.ex
  lib/glific_web/router.ex
  test/glific_web/flows/flow_editor_controller_test.exs
Labels: enhancement

#2122 Hotfix/saved-search
  .github/workflows/continuous-integration.yml
  lib/glific/clients/arogya_world.ex
  lib/glific/messages.ex
  lib/glific/searches/full.ex
  mix.exs
Labels: bug

#2124 Feature/copy-interactive-template
  api.docs/includes/_interactive.md
  assets/gql/interactives/copy.gql
  lib/glific/flows.ex
  lib/glific/templates/interactive_templates.ex
  lib/glific_web/resolvers/flows.ex
  lib/glific_web/resolvers/interactives.ex
  lib/glific_web/schema/interactive_template_types.ex
  test/glific/flows_test.exs
  test/glific/interactive_templates_test.exs
  test/glific_web/schema/interactive_template_test.exs
Labels: enhancement

#2117 Enterprise template msg
  README.md
  api.docs/includes/_session_templates.md
  lib/glific/jobs/minute_worker.ex
  lib/glific/providers/gupshup/template.ex
  lib/glific/providers/gupshup/worker.ex
  lib/glific/providers/gupshup_enterprise/api_client.ex
  lib/glific/providers/gupshup_enterprise/template.ex
  lib/glific/providers/gupshup_enterprise/worker.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific/seeds/seeds_migration.ex
  lib/glific/templates.ex
  lib/glific/templates/session_templates.ex
  lib/glific_web/resolvers/templates.ex
  lib/glific_web/schema/session_template_type.ex
  priv/repo/migrations/20220314060653_add_enterprise_template_id_to_session_templates.exs
  test/glific/messages_test.exs
  test/glific/templates_test.exs
  test/support/fixtures.ex
Labels: enhancement

#2126 Feature/enterprise credentials
  lib/glific/partners.ex
  lib/glific/providers/gupshup_enterprise/api_client.ex
  lib/glific/providers/gupshup_enterprise/template.ex
  priv/repo/migrations/20220105070545_gupshup_enterprise.exs
  priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs
  test/support/fixtures.ex
Labels: enhancement

#2132 Gupshup-Enterprise/webhook support for buttons
  lib/glific/providers/gupshup_enterprise/message.ex
  lib/glific_web/providers/gupshup_enterprise/message_controller.ex
  lib/glific_web/providers/gupshup_enterprise/router.ex
Labels: enhancement

#2150 Feature/gupshup enterprise quick reply
  lib/glific/providers/gupshup_enterprise/api_client.ex
  lib/glific/providers/gupshup_enterprise/message.ex
  lib/glific_web/providers/gupshup_enterprise/message_controller.ex
Labels: enhancement

#2161 Hotfix/interactive-msg-ids
  lib/glific/providers/gupshup_enterprise/message.ex
Labels: bug
