Repository glific/glific, pull requests merged in 2022-12, with the labels that each got.

#2599 Flows: Import/Export Interactive Templates
  lib/glific/flows.ex
  test/glific_web/schema/flow_test.exs
Labels: enhancement

#2608 Bigquery: increasing timeout for max_last_update
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: bug

#2611 Erase: Webhooks, Message Conversations and Flow contexts
  lib/glific/erase.ex
  rel/overlays/Procfile
Labels: enhancement

#2613 Messages: added empty body check
  lib/glific/flows/contact_action.ex
  lib/glific/messages.ex
Labels: enhancement

#2615 BigQuery: Clean logs
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: enhancement

#2616 BigQuery: Sync Delays
  config/config.exs
  lib/glific/partners.ex
Labels: enhancement

#2622 Nayidisha: sending english content as default
  lib/glific/clients/nayi_disha.ex
Labels: consulting

#2623 Enhancement/google sheet
  Postman Collections/api.docs_postman/api_collection.json.json
  api.docs/includes/_sheets.md
  lib/glific/third_party/sheets/sheet.ex
  lib/glific/third_party/sheets/sheets.ex
  test/glific/sheets_test.exs
  test/glific_web/schema/sheet_test.exs
  test/support/fixtures.ex
Labels: enhancement

#2631 Gsheet: Hotfix
  lib/glific/third_party/sheets/sheets.ex
Labels: bug

#2629 Flows: Save Flow Results node
  lib/glific/flows/action.ex
Labels: bug

#2628 Tap school id changes
  lib/glific/clients/tap.ex
Labels: consulting
