Repository glific/glific, pull requests merged in 2022-06, with the labels that each got.

#2267 Disable Chatbase from listing
  api.docs/includes/_organizations.md
  lib/glific/partners.ex
  lib/glific/seeds/seeds_dev.ex
  test/glific_web/schema/organization_test.exs
  test/glific_web/schema/provider_test.exs
Labels: enhancement

#2275 Feature/profile
  api.docs/includes/_organizations.md
  assets/gql/profiles/create_profile.gql
  assets/gql/profiles/delete_profile.gql
  assets/gql/profiles/fields.frag.gql
  assets/gql/profiles/update_profile.gql
  lib/glific/contacts/contact.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific/profiles.ex
  lib/glific/profiles/profile.ex
  lib/glific_web/resolvers/profiles.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/organization_types.ex
  lib/glific_web/schema/profile_types.ex
  priv/repo/migrations/20220606122101_create_profiles.exs
  priv/repo/seeds/20200723172939_add_glific_data.exs
  test/glific/profiles_test.exs
  test/glific_web/schema/profile_test.exs
  test/support/fixtures.ex
Labels: enhancement

#2276 Feature/big query fix
  lib/glific/partners.ex
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/gcs/gcs.ex
  test/glific/bigquery_test.exs
Labels: enhancement

#2277 Feature/profile search
  assets/gql/profiles/by_id.gql
  assets/gql/profiles/list.gql
  lib/glific/profiles.ex
  lib/glific/profiles/profile.ex
  lib/glific_web/resolvers/profiles.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/profile_types.ex
  priv/repo/migrations/20220609073705_update_profile_migration.exs
  test/glific/profiles_test.exs
  test/glific_web/schema/profile_test.exs
Labels: enhancement

#2284 Feature/kef sheets
  lib/glific/clients/kef.ex
Labels: consulting

#2291 Feature/profile update
  api.docs/includes/_profiles.md
  assets/gql/profiles/fields.frag.gql
  assets/gql/profiles/list.gql
  lib/glific/profiles/profile.ex
  lib/glific_web/schema/profile_types.ex
  priv/repo/migrations/20220615045615_profile_fields_update.exs
  test/glific/profiles_test.exs
Labels: enhancement

#2292 KEF report messages changes for different language
  lib/glific/clients/kef.ex
Labels: ready for review, consulting

#2279 flow editor controller improvement
  lib/glific/flows/flow_label.ex
  lib/glific_web/flows/flow_editor_controller.ex
Labels: enhancement

#2288 Contact Profile Flow-Editor Support
  api.docs/includes/_profiles.md
  assets/gql/profiles/fields.frag.gql
  lib/glific/contacts.ex
  lib/glific/contacts/contact.ex
  lib/glific/flows/action.ex
  lib/glific/flows/contact_field.ex
  lib/glific/partners.ex
  lib/glific/profiles.ex
  lib/glific/profiles/profile.ex
  lib/glific_web/schema/organization_types.ex
  lib/glific_web/schema/profile_types.ex
  priv/data/flows/completion.json
  priv/repo/migrations/20220606122101_create_profiles.exs
  priv/repo/migrations/20220615045615_profile_fields_update.exs
  priv/repo/migrations/20220616055250_update_profile_fields.exs
  priv/repo/seeds/20200723172939_add_glific_data.exs
  test/glific/contact_profile_test.exs
  test/glific/flows/action_test.exs
  test/glific/profiles_test.exs
  test/glific_web/schema/profile_test.exs
  test/support/fixtures.ex
Labels: enhancement

#2293 Feature/sync profile with bigquery
  .iex.exs
  lib/glific/clients/kef.ex
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific_web/flows/flow_editor_controller.ex
Labels: enhancement
