Repository glific/glific, pull requests merged in 2022-04, with the labels that each got.

#2153 Feature/Partner api
  api.docs/includes/_providers.md
  assets/gql/providers/quality_rating.gql
  config/.env.dev.txt
  lib/glific/caches.ex
  lib/glific/partners.ex
  lib/glific/partners/saas.ex
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific_web/resolvers/partners.ex
  lib/glific_web/schema/provider_types.ex
  priv/repo/migrations/20220331123334_add_isv_credentials_to_saas_table.exs
  priv/repo/seeds/20200723172939_add_glific_data.exs
  test/glific_web/schema/provider_test.exs
Labels: enhancement

#2188 Gupshup Enterprise: Message Event Handling
  lib/glific_web/providers/gupshup_enterprise/controllers/default_controller.ex
  lib/glific_web/providers/gupshup_enterprise/controllers/message_controller.ex
  lib/glific_web/providers/gupshup_enterprise/controllers/message_event_controller.ex
  lib/glific_web/providers/gupshup_enterprise/router.ex
  lib/glific_web/providers/gupshup_enterprise/shunt.ex
  test/glific_web/providers/gupshup_enterprise/controllers/message_controller_test.exs
  test/glific_web/providers/gupshup_enterprise/controllers/message_event_controller_test.exs
Labels: enhancement, ready for review

#2191 Hotfix/enterprise templates
  lib/glific/providers/gupshup_enterprise/api_client.ex
Labels: bug

#2192 Issues/#2077
  lib/glific.ex
  lib/glific/searches/full.ex
  lib/glific_web/schema/search_type.ex
  mix.lock
  test/glific_web/schema/search_test.exs
Labels: enhancement

#2200 Bug/export-flow
  lib/glific/flows.ex
Labels: bug

#2202 Broadcast id in message type
  api.docs/includes/_messages.md
  lib/glific/messages/message.ex
  lib/glific_web/schema/message_types.ex
Labels: enhancement

#2216 Feature/template error reasons
  api.docs/includes/_session_templates.md
  lib/glific/templates.ex
  lib/glific/templates/session_templates.ex
  lib/glific_web/schema/session_template_type.ex
  priv/repo/migrations/20220421053535_add_reason_to_session_templates.exs
  test/glific/templates_test.exs
Labels: enhancement

#2204 sending broadcast error count
  api.docs/includes/_flows.md
  assets/gql/flows/broadcast_stats.gql
  lib/glific/flows/broadcast.ex
  test/glific_web/schema/flow_test.exs
Labels: documentation, bug

#2225 Enterprise/Optin
  lib/glific/providers/gupshup_enterprise/api_client.ex
Labels: bug
