Repository glific/glific, pull requests merged in 2022-09, with the labels that each got.

#2420 Roles and Permission: Phase 2
  api.docs/includes/_flows.md
  api.docs/includes/_groups.md
  lib/glific/access_control.ex
  lib/glific/access_control/group_role.ex
  lib/glific/groups.ex
  lib/glific/groups/group.ex
  lib/glific_web/schema/contact_types.ex
  lib/glific_web/schema/group_types.ex
  priv/repo/migrations/20220905054418_add_groups_permissions.exs
  test/glific/access_control_test.exs
Labels: enhancement

#2423 Feature/roles permission phase 2 triggers
  api.docs/includes/_triggers.md
  lib/glific/access_control.ex
  lib/glific/access_control/trigger_role.ex
  lib/glific/triggers.ex
  lib/glific/triggers/trigger.ex
  lib/glific_web/resolvers/triggers.ex
  lib/glific_web/schema/trigger_types.ex
  priv/repo/migrations/20220905054418_add_groups_permissions.exs
  test/glific/access_control_test.exs
  test/glific/triggers_test.exs
  test/glific_web/schema/trigger_test.exs
  test/support/fixtures.ex
Labels: enhancement

#2424 changed query to mutation
  assets/gql/session_templates/sync.gql
  lib/glific_web/schema/session_template_type.ex
Labels: enhancement

#2427 Profiles: Saving contact fields to first profile
  lib/glific/profiles.ex
Labels: enhancement

#2430 Send message as broadcast
  api.docs/includes/_flows.md
  api.docs/includes/_messages.md
  assets/gql/flows/broadcast_stats.gql
  assets/gql/flows/group_flow.gql
  assets/gql/messages/send_hsm_message_to_group.gql
  lib/glific/communications/message.ex
  lib/glific/flows.ex
  lib/glific/flows/broadcast.ex
  lib/glific/flows/broadcast/message_broadcast.ex
  lib/glific/flows/broadcast/message_broadcast_contact.ex
  lib/glific/flows/contact_action.ex
  lib/glific/flows/flow_context.ex
  lib/glific/messages.ex
  lib/glific/messages/message.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific_web/resolvers/flows.ex
  lib/glific_web/resolvers/messages.ex
  lib/glific_web/schema/flow_types.ex
  lib/glific_web/schema/message_types.ex
  priv/repo/migrations/20220906140729_update_flow_broadcast_table.exs
  test/glific/flows_test.exs
  test/glific_web/schema/flow_test.exs
  test/glific_web/schema/message_test.exs
Labels: ready for review

#2445 Feature/filter added
  api.docs/includes/_messages.md
  lib/glific/messages.ex
  lib/glific_web/schema/message_types.ex
  test/glific/messages_test.exs
  test/glific_web/schema/message_test.exs
Labels: ready for review

#2434 Triggers: Hotfix for monthly trigger without date
  assets/gql/triggers/fields.frag.gql
  lib/glific/triggers/helper.ex
  lib/glific/triggers/trigger.ex
  test/glific/triggers_test.exs
  test/glific_web/schema/trigger_test.exs
  test/support/fixtures.ex
Labels: ready for review, bug

#2454 Profile: Hotfix for profile switching
  lib/glific/profiles.ex
  test/glific/profiles_test.exs
Labels: bug

#2457 Appsignal: Flow required fields
  lib/glific/flows.ex
Labels: bug

#2461 Disable automatic template approval for new organization
  lib/glific/saas/onboard.ex
  test/glific/partners/onboard_test.exs
Labels: bug

#2463 Consulting: Reapbenefit
  lib/glific/clients/reap_benefit.ex
Labels: consulting

#2459 Flows: Validation for flow keywords
  lib/glific/flows/case.ex
  lib/glific/flows/flow.ex
  priv/data/flows/test.json
  test/glific/flows_test.exs
Labels: enhancement

#2468 Flow validation
  lib/glific/flows/case.ex
  priv/data/flows/test.json
Labels: bug

#2470 Enhancements: Message conversation
  lib/glific/messages/message_conversation.ex
  lib/glific/providers/gupshup/message.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  priv/repo/migrations/20220823091156_add_message_conversations.exs
Labels: enhancement

#2475 Flows: Restricting inactive flows
  lib/glific/flows.ex
  lib/glific/flows/flow.ex
  test/glific/flows_test.exs
  test/glific_web/schema/flow_test.exs
Labels: enhancement

#2480 Enhancement: Flow Editor Case validation
  lib/glific/flows/case.ex
  lib/glific/flows/flow.ex
  lib/glific/flows/localization.ex
  lib/glific/flows/node.ex
  lib/glific/flows/router.ex
  priv/data/flows/test.json
Labels: enhancement

#2476 Bigquery: Syncing broadcast tables
  lib/glific/third_party/asr/google_asr.ex
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific/third_party/gcs/gcs.ex
  lib/glific/third_party/navanatech/navanatech.ex
  lib/glific/third_party/sheets/api_client.ex
Labels: enhancement

#2485 Enhancement: Gupshup Enterprise Templates
  lib/glific/messages.ex
  lib/glific/partners/provider.ex
  lib/glific/providers/bsp_worker.ex
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific/providers/gupshup/response_handler.ex
  lib/glific/providers/gupshup_enterprise/message.ex
  lib/glific/providers/gupshup_enterprise/response_handler.ex
  lib/glific/providers/gupshup_enterprise/template.ex
  lib/glific/providers/gupshup_enterprise/worker.ex
  test/glific/templates_test.exs
Labels: enhancement

#2489 Dg Telangana changes
  lib/glific/clients/digital_green.ex
Labels: ready for review, consulting

#2491 Bigquery: Insufficient Permission issue
  lib/glific/partners.ex
  lib/glific/third_party/bigquery/bigquery.ex
  test/glific/bigquery_test.exs
  test/glific/partners/partners_test.exs
Labels: bug
