Repository glific/glific, pull requests merged in 2022-11, with the labels that each got.

#2554 Google Sheet: Sheet validation
  lib/glific/third_party/sheets/sheet.ex
Labels: enhancement

#2548 Added Dockerfile and compose yaml
  Dockerfile
  docker-compose.yaml
Labels: enhancement

#2564 Google Sheet: Parsing sheet row variable
  lib/glific/third_party/sheets/sheets.ex
Labels: enhancement

#2565 Extensions
  lib/glific/clients.ex
  lib/glific/clients/digital_green_jharkhand.ex
  lib/glific/messages.ex
Labels: consulting

#2569 Seeder: Adding contact fields to seeders
  lib/glific/seeds/seeds_scale.ex
Labels: enhancement

#2572 Stripe: Hotfixes for recent API changes
  lib/glific/partners/billing.ex
Labels: bug

#2576 Dg weather changes
  lib/glific/clients/digital_green.ex
Labels: consulting

#2584 Client file for OBLF
  lib/glific/clients.ex
  lib/glific/clients/oblf.ex
Labels: ready for review, consulting
