Repository glific/glific, pull requests merged in 2022-08, with the labels that each got.

#2340 Pinning flows in Flows screen
  api.docs/includes/_flows.md
  assets/gql/flows/fields.frag.gql
  assets/gql/flows/list.gql
  lib/glific/flows.ex
  lib/glific/flows/flow.ex
  lib/glific/partners.ex
  lib/glific_web/schema/flow_types.ex
  priv/repo/migrations/20220725085345_update_flows_is_pinned.exs
  test/glific/flows_test.exs
  test/glific/partners/partners_test.exs
  test/glific_web/schema/flow_test.exs
Labels: enhancement

#2326 Error fixed
  lib/glific/flows.ex
  test/glific/flows_test.exs
Labels: ready for review

#2354 Flow: Take Over
  api.docs/includes/_flows.md
  lib/glific/state/flow.ex
  lib/glific/state/simulator.ex
  lib/glific/state/state.ex
  lib/glific_web/resolvers/flows.ex
  lib/glific_web/schema/flow_types.ex
  test/glific/state_test.exs
Labels: enhancement

#2357 Delete contact restriction
  lib/glific/contacts.ex
  test/glific/contacts_test.exs
Labels: enhancement

#2365 Feature/appsignal issues
  lib/glific/flows/templating.ex
  lib/glific/messages.ex
  lib/glific/third_party/dialogflow/sessions.ex
  test/glific/flows/action_test.exs
Labels: ready for review

#2250 Roles and permissions
  assets/gql/roles/by_id.gql
  assets/gql/roles/count.gql
  assets/gql/roles/create.gql
  assets/gql/roles/delete.gql
  assets/gql/roles/fields.frag.gql
  assets/gql/roles/list.gql
  assets/gql/roles/update.gql
  assets/gql/users/list_roles.gql
  lib/glific/access_control.ex
  lib/glific/access_control/flow_role.ex
  lib/glific/access_control/permission.ex
  lib/glific/access_control/role.ex
  lib/glific/access_control/user_role.ex
  lib/glific/enums/constants/enums.ex
  lib/glific/enums/enums.ex
  lib/glific/flows.ex
  lib/glific/flows/flow.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific/seeds/seeds_migration.ex
  lib/glific/settings/language.ex
  lib/glific/users.ex
  lib/glific/users/user.ex
  lib/glific_web/resolvers/roles.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/flow_types.ex
  lib/glific_web/schema/organization_types.ex
  lib/glific_web/schema/role_types.ex
  lib/glific_web/schema/users_types.ex
  priv/repo/migrations/20220509103325_create_role_permissions.exs
  test/glific/access_control_test.exs
  test/glific_web/schema/role_test.exs
  test/glific_web/schema/user_test.exs
  test/support/fixtures.ex
Labels: enhancement

#2372 Pull organisation services even the org is suspended.
  lib/glific/flows/templating.ex
  lib/glific/partners.ex
  lib/glific_web/resolvers/partners.ex
  test/glific/partners/partners_test.exs
Labels: ready for review

#2375 Hotfix/User role mapping
  lib/glific/users.ex
Labels: bug

#2381 HSM template fixes
  lib/glific/flows/templating.ex
Labels: bug

#2382 Roles and Permission: Seeder Fixes
  lib/glific/seeds/seeds_dev.ex
  lib/glific/users.ex
  priv/repo/seeds/20200723172939_add_glific_data.exs
  test/glific/access_control_test.exs
  test/glific_web/schema/role_test.exs
  test/glific_web/schema/user_test.exs
Labels: bug

#2394 Update Error message
  lib/glific_web/resolvers/messages.ex
Labels: enhancement

#2390 fixed typo
  README.md
Labels: enhancement

#2388 Consulting: RB frappe webhook
  lib/glific/clients.ex
  lib/glific/clients/reap_benefit.ex
Labels: consulting

#2396 Message Conversations
  lib/glific/clients/reap_benefit.ex
  lib/glific/message_conversations.ex
  lib/glific/messages/message_conversation.ex
  lib/glific/providers/gupshup/message.ex
  lib/glific/providers/message_behaviour.ex
  lib/glific_web/providers/gupshup/controllers/billing_event_controller.ex
  lib/glific_web/providers/gupshup/controllers/message_controller.ex
  lib/glific_web/providers/gupshup/plugs/shunt.ex
  lib/glific_web/providers/gupshup/router.ex
  priv/repo/migrations/20220823091156_add_message_conversations.exs
  test/glific/message_conversations_test.exs
  test/glific_web/providers/gupshup/controllers/billing_event_controller_test.exs
  test/support/fixtures.ex
Labels: enhancement

#2368 Feature/hsm template
  assets/gql/session_templates/sync.gql
  lib/glific/providers/gupshup/template.ex
  lib/glific/templates.ex
  lib/glific_web/resolvers/templates.ex
  lib/glific_web/schema/session_template_type.ex
  test/glific_web/schema/session_template_test.exs
Labels: In-Progress

#2400 Message Conversations: disabling logs
  lib/glific/providers/gupshup/message.ex
  lib/glific/providers/message_behaviour.ex
  lib/glific_web/providers/gupshup/controllers/billing_event_controller.ex
  test/glific_web/providers/gupshup/controllers/billing_event_controller_test.exs
Labels: enhancement

#2402 Profiles: adding support to capture prefered language
  lib/glific/flows/contact_field.ex
  lib/glific/flows/contact_setting.ex
  test/glific/flows/action_test.exs
  test/glific/flows/contact_setting_test.exs
  test/support/fixtures.ex
Labels: enhancement

#2406 Optin Flow: Updated with interactive template
  lib/glific/seeds/seeds_dev.ex
  lib/glific/seeds/seeds_flows.ex
  priv/data/flows/optin.json
  test/glific/flows_test.exs
  test/glific/interactive_templates_test.exs
  test/glific/processor/consumer_flow_test.exs
Labels: enhancement

#2408 Profiles: storing profile level info across tables
  priv/repo/migrations/20220826061242_add_profile_id_to_flow_tables.exs
Labels: enhancement

#2414 Profile: APIs
  api.docs/includes/_contacts.md
  api.docs/includes/_profiles.md
  lib/glific/contacts.ex
  lib/glific/contacts/contact.ex
  lib/glific/contacts/contact_history.ex
  lib/glific_web/schema/contact_types.ex
  lib/glific_web/schema/profile_types.ex
  test/glific/profiles_test.exs
  test/glific_web/schema/contact_test.exs
Labels: enhancement

#2418 Frappe webhook
  lib/glific/clients/reap_benefit.ex
Labels: consulting
