Repository glific/glific, pull requests merged in 2022-10, with the labels that each got.

#2492 Gupshup Enterprise: Media interactive msg
  lib/glific/messages/message.ex
  lib/glific/providers/gupshup/api_client.ex
  lib/glific/providers/gupshup_enterprise/api_client.ex
  lib/glific/providers/gupshup_enterprise/message.ex
  lib/glific_web/resolvers/messages.ex
Labels: enhancement

#2499 Gupshup Enterprise: Media Templates
  lib/glific/providers/gupshup_enterprise/api_client.ex
  lib/glific/providers/gupshup_enterprise/message.ex
  lib/glific/providers/gupshup_enterprise/worker.ex
Labels: enhancement

#2506 Adding location while creating a user in frappe
  lib/glific/clients/reap_benefit.ex
Labels: consulting

#2509 Bigquery: Syncing message groups
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: enhancement

#2511 Contact Groups: Timestamps
  priv/repo/migrations/20221011082819_add_timestamp_to_contact_groups.exs
Labels: enhancement

#2514 Re indexer oban jobs
  config/config.exs
  lib/glific/erase.ex
  lib/glific/groups/contact_group.ex
  lib/glific/jobs/minute_worker.ex
Labels: enhancement

#2520 Fix typos in README
  README.md
Labels: ready for review

#2516 Google Sheets
  coveralls.json
  lib/glific/clients/digital_green.ex
  lib/glific/flows/webhook_log.ex
  lib/glific/mails/mail_log.ex
  lib/glific/stats.ex
  lib/glific/third_party/sheets/sheet.ex
  lib/glific/third_party/sheets/sheet_data.ex
  lib/glific/third_party/sheets/sheets.ex
  lib/glific_web/resolvers/sheets.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/group_types.ex
  lib/glific_web/schema/search_type.ex
  lib/glific_web/schema/sheet_types.ex
  lib/glific_web/schema/trigger_types.ex
  priv/repo/migrations/20221012062208_add_sheets.exs
Labels: enhancement

#2522 Feature/Google sheets APIs
  api.docs/includes/_sheets.md
  lib/glific/third_party/sheets/sheets.ex
  lib/glific_web/resolvers/contacts.ex
  lib/glific_web/resolvers/sheets.ex
  lib/glific_web/schema/sheet_types.ex
Labels: enhancement

#2532 Google Sheets: Added sync sheet API
  .doctor.exs
  api.docs/includes/_sheets.md
  lib/glific/flows/message_vars_parser.ex
  lib/glific/third_party/sheets/sheets.ex
  lib/glific_web/resolvers/contacts.ex
  lib/glific_web/resolvers/sheets.ex
  lib/glific_web/schema/sheet_types.ex
Labels: enhancement

#2538 Client file initiation for the Dg jharkhand
  lib/glific/clients.ex
  lib/glific/clients/digital_green_jharkhand
Labels: ready for review

#2541 Google Sheet: Added Flow API for sheets
  lib/glific.ex
  lib/glific/flows/action.ex
  lib/glific/templates/interactive_templates.ex
  lib/glific_web/flows/flow_editor_controller.ex
  lib/glific_web/router.ex
  lib/glific_web/tenants.ex
  priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs
  priv/repo/seeds/20201006012223_v0_5_0_alter_glific_data.exs
Labels: enhancement

#2542 Consulting: PehlayAkshar
  lib/glific/clients.ex
  lib/glific/clients/pehlay_akshar.ex
Labels: consulting

#2550 Sort messages based on last message at
  lib/glific/searches.ex
Labels: ready for review

#2540 Google Sheet: New Flow editor node
  lib/glific/clients.ex
  lib/glific/flows/action.ex
  lib/glific/flows/flow_context.ex
  lib/glific/third_party/sheets/sheets.ex
  priv/repo/migrations/20221012062208_add_sheets.exs
Labels: enhancement

#2546 Google Sheets: Testcases
  assets/gql/sheets/by_id.gql
  assets/gql/sheets/count.gql
  assets/gql/sheets/create.gql
  assets/gql/sheets/delete.gql
  assets/gql/sheets/fields.frag.gql
  assets/gql/sheets/list.gql
  assets/gql/sheets/update.gql
  coveralls.json
  lib/glific/clients/pehlay_akshar.ex
  lib/glific/third_party/sheets/sheet.ex
  test/glific/message_conversations_test.exs
  test/glific/sheets_test.exs
  test/glific_web/schema/sheet_test.exs
  test/support/fixtures.ex
Labels: Testcase
