Repository glific/glific, pull requests merged in 2023-10, with the labels that each got.

#3139 Contact:Remove_status from read only
  lib/glific_web/resolvers/contacts.ex
  lib/glific_web/templates/dashboard/dashboard.html.heex
Labels: ready for review

#3137 kef new webhooks
  lib/glific/clients/kef.ex
Labels: ready for review

#3141 Bug: Ticketing Schema
  priv/repo/structure.sql
Labels: bug

#3148 Templates: Updating seed OTP template
  lib/glific/seeds/seeds_migration.ex
  test/glific/partners/onboard_test.exs
  test/glific/templates_test.exs
  test/support/fixtures.ex
Labels: enhancement

#3152 Mail V3: Replaced Graphs in Mail with Numeric Metric
  lib/glific/stats.ex
  lib/glific_web/templates/dashboard/dashboard.html.heex
Labels: ready for review

#3149 Ticketing System:Bulk closure
  lib/glific/tickets.ex
  lib/glific_web/resolvers/tickets.ex
  lib/glific_web/schema/ticket_types.ex
  test/glific_web/schema/ticket_test.exs
Labels: enhancement

#3161 Session Template: Server side validation
  lib/glific/templates/session_templates.ex
  lib/glific/tickets.ex
  test/glific_web/schema/session_template_test.exs
Labels: ready for review
