Repository glific/glific, pull requests merged in 2023-11, with the labels that each got.

#3175 KEF: Webhook fixes
  lib/glific/clients/kef.ex
Labels: bug

#3182 Ticketing System: Syncing to BQ
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: enhancement

#3178 Session Template: Import template check existing template UUID
  lib/glific/templates.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  test/glific/templates_test.exs
Labels: ready for review

#3186 feature/Support Tickets: add the filter for phone and name
  lib/glific/tickets.ex
  test/glific_web/schema/ticket_test.exs
Labels: ready for review

#3192 fix/Login:handle error message in forgot password
  lib/glific_web/controllers/api/v1/registration_controller.ex
  test/glific_web/registration_controller_test.exs
Labels: ready for review

#3130 Flow:Import Error Message
  assets/gql/flows/import_flow.gql
  lib/glific/flows.ex
  lib/glific_web/resolvers/flows.ex
  lib/glific_web/schema/flow_types.ex
  test/glific_web/schema/flow_test.exs
Labels: ready for review

#3206 lets restructure cron jobs, optimize it so things run
  lib/glific/erase.ex
  lib/glific/flows/flow_context.ex
  lib/glific/jobs/minute_worker.ex
  test/glific/flows/flow_context_test.exs
Labels: bug

#3232 Ticketing System: Adding message number to tickets
  lib/glific/providers/balance_worker.ex
  lib/glific/tickets.ex
  lib/glific/tickets/ticket.ex
  priv/repo/migrations/20231122115923_add_message_number_colum_in_ticket_table.exs
  test/glific/tickets_test.exs
  test/glific_web/schema/ticket_test.exs
Labels: ready for review

#3209 Features/upgrade
  .github/workflows/continuous-integration.yml
  .tool-versions
  config/config.exs
  config/test.exs
  lib/glific_web/templates/layout/root.html.heex
  mix.exs
  mix.lock
  priv/repo/migrations/20231118000016_upgrade_oban_16.exs
  test/glific/bigquery_test.exs
  test/glific/communications_test.exs
  test/glific/conversations_group_test.exs
  test/glific/conversations_test.exs
  test/glific/dialogflow/sessions_test.exs
  test/glific/flows/webhook_test.exs
  test/glific/messages_test.exs
  test/glific/triggers_test.exs
Labels: enhancement

#3212 Bugs/interactive templates
  lib/glific/flows/action.ex
  lib/glific/flows/contact_action.ex
  lib/glific/flows/templating.ex
  lib/glific/flows/wait.ex
  lib/glific/providers/balance_worker.ex
  lib/glific/templates/interactive_templates.ex
  lib/glific_web/resolvers/flows.ex
  priv/data/flows/test.json
  test/glific/flows_test.exs
Labels: bug

#3184 Interactive Message: Add location interactive msg
  lib/glific/communications/message.ex
  lib/glific/enums/constants/enums.ex
  lib/glific/enums/enums.ex
  lib/glific/messages.ex
  lib/glific/messages/message.ex
  lib/glific/providers/balance_worker.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific/templates/interactive_templates.ex
  priv/repo/structure.sql
  test/glific/messages_test.exs
  test/glific_web/schema/interactive_template_test.exs
Labels: enhancement
