Repository glific/glific, pull requests merged in 2023-05, with the labels that each got.

#2760 PA - Quiz flow webhook changes
  lib/glific/clients/pehlay_akshar.ex
Labels: ready for review

#2789 Feature/ticketing
  lib/glific/contacts/contact.ex
  lib/glific/tickets.ex
  lib/glific/tickets/ticket.ex
  lib/glific/users.ex
  priv/repo/migrations/20230512175955_create_tickets.exs
  test/glific/tickets_test.exs
  test/support/fixtures/tickets_fixtures.ex
Labels: enhancement

#2791 Ticketing: CRUD APIs
  assets/gql/tickets/by_id.gql
  assets/gql/tickets/count.gql
  assets/gql/tickets/create.gql
  assets/gql/tickets/delete.gql
  assets/gql/tickets/fields.frag.gql
  assets/gql/tickets/list.gql
  assets/gql/tickets/update.gql
  lib/glific/tickets.ex
  lib/glific/tickets/ticket.ex
  lib/glific_web/resolvers/tickets.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/ticket_types.ex
  test/glific/tickets_test.exs
  test/glific_web/schema/ticket_test.exs
  test/support/fixtures/tickets_fixtures.ex
Labels: enhancement

#2781 Added simple UI fixes for dashboard
  lib/glific_web/templates/layout/_user_menu.html.heex
  lib/glific_web/templates/layout/app.html.heex
  lib/glific_web/templates/layout/live.html.heex
  lib/glific_web/templates/layout/root.html.heex
  lib/glific_web/templates/live/stats_live.html.heex
  lib/glific_web/templates/user_session/new.html.heex
Labels: bug

#2795 Feature: ASR common webhook
  lib/glific/clients/common_webhook.ex
  lib/glific/clients/lahi.ex
  lib/glific/clients/suno_sunao.ex
  lib/glific/third_party/asr/google_asr.ex
Labels: enhancement

#2796 Ticketing: New node
  lib/glific/flows/action.ex
  lib/glific/flows/flow_label.ex
  lib/glific/misc/flags.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific/tickets.ex
  lib/glific_web/flows/flow_editor_controller.ex
  lib/glific_web/router.ex
  lib/glific_web/schema/organization_types.ex
  priv/repo/migrations/20230522105210_create_topic.exs
  test/glific/flows/action_test.exs
  test/glific_web/flows/flow_editor_controller_test.exs
Labels: enhancement
