Repository glific/glific, pull requests merged in 2023-06, with the labels that each got.

#2803 KEF webhook changes
  lib/glific/clients/kef.ex
Labels: ready for review

#2809 Feature/ticketing services apis
  lib/glific/partners.ex
  lib/glific_web/schema/organization_types.ex
  lib/glific_web/schema/ticket_types.ex
  mix.exs
Labels: enhancement

#2812 Webhooks: Using common webhooks in Clients file
  lib/glific/clients/bandhu.ex
  lib/glific/clients/lahi.ex
  lib/glific/clients/suno_sunao.ex
Labels: enhancement

#2811 KEF - added new webhook
  lib/glific/clients/kef.ex
Labels: enhancement, consulting

#2819 School name fix for - TAP
  lib/glific/clients/tap.ex
Labels: ready for review, consulting

#2823 ChatGPT: Added support for voice gpt
  lib/glific/clients/bandhu.ex
  lib/glific/clients/common_webhook.ex
Labels: enhancement

#2816 Added trackers data into the BQ
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: enhancement, ready for review

#2825 ChatGPT: Voice GPT enhancement
  lib/glific/clients/common_webhook.ex
Labels: enhancement

#2833 Bug: Saved flow revision getting lost
  lib/glific/flows.ex
Labels: bug

#2836 Flows: Added flow revision author
  lib/glific/flows.ex
  lib/glific/flows/flow_revision.ex
  lib/glific_web/flows/flow_editor_controller.ex
  lib/glific_web/resolvers/flows.ex
  priv/repo/migrations/20230616045651_add_flow_revision_author.exs
  test/glific/erase_test.exs
  test/glific/flows_test.exs
Labels: enhancement

#2840 GPT: Adding prompt option
  lib/glific/clients/common_webhook.ex
Labels: enhancement

#2832 Docker
  .dockerignore
  Dockerfile
  README.md
  config/.env.dev.txt
  config/dev.exs
  config/entrypoint.sh
Labels: enhancement

#2842 Category filter for templates
  lib/glific/templates.ex
  lib/glific_web/schema/session_template_type.ex
  test/glific_web/schema/session_template_test.exs
Labels: enhancement

#2843 Enhancement: Template allow category change
  lib/glific/providers/gupshup/partner/partner_api.ex
Labels: enhancement

#2849 added label column to flows table
  lib/glific/flows.ex
  lib/glific/flows/flow.ex
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific_web/schema/flow_types.ex
  priv/repo/migrations/20230627145331_add_labels_to_flows.exs
  test/glific/flows_test.exs
  test/glific_web/schema/session_template_test.exs
Labels: enhancement

#2856 sync template categories based on new guidelines
  lib/glific/templates.ex
  test/glific/flows_test.exs
  test/glific_web/schema/session_template_test.exs
Labels: C4GT Community
