Repository glific/glific, pull requests merged in 2023-07, with the labels that each got.

#2854 Bug/2666
  assets/gql/contacts/move.gql
  lib/glific/contacts.ex
  lib/glific/contacts/import.ex
  lib/glific_web/resolvers/contacts.ex
  lib/glific_web/schema/contact_types.ex
  test/glific/contacts_test.exs
  test/glific_web/schema/contact_test.exs
Labels: C4GT Community

#2853 Enhancement: Editing Approved Templates
  config/dev.secret.exs.txt
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific/providers/gupshup/template.ex
  lib/glific/templates.ex
  lib/glific_web/resolvers/templates.ex
  lib/glific_web/schema/session_template_type.ex
  test/glific/templates_test.exs
Labels: enhancement

#2864 Feature/export
  assets/gql/export/config.gql
  assets/gql/export/data.gql
  assets/gql/export/stats.gql
  lib/glific/partners/export.ex
  lib/glific_web/resolvers/partners.ex
  lib/glific_web/schema/organization_types.ex
  test/glific/partners/export_test.exs
  test/glific_web/schema/export_test.exs
Labels: enhancement

#2870 Paf leaderboard changes
  lib/glific/clients/pehlay_akshar.ex
Labels: ready for review

#2887 Add pie chart for inbound and outbound messages
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: C4GT Community

#2895 Add card for non opted contacts
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: C4GT Community

#2894 Add Cards for Monthly Flows
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: C4GT Community

#2902 Exports: fixes for endtime
  lib/glific/partners/export.ex
Labels: bug

#2905 sending API error for gsheet
  lib/glific/third_party/sheets/google_sheets.ex
  lib/glific/third_party/sheets/sheets.ex
  lib/glific_web/plugs/api_auth_plug.ex
Labels: bug

#2896 Add Cards for Monthly Incoming, Outgoing and HSM Messages
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: C4GT Community

#2928 fixed notification and error message queries to be monthly
  lib/glific/reports.ex
Labels: bug

#2918 Updated OrganizationExportData API to return data field as JSON string
  lib/glific/partners/export.ex
  lib/glific/reports.ex
  test/glific_web/schema/export_test.exs
Labels: enhancement

#2921 Add Cards for Flows Started and Completed
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: C4GT Community

#2927 fix query to retrieve monthly stats
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: enhancement

#2937 Add pie chart for contacts in session
  assets/js/hooks.js
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: C4GT Community

#2926 Added table for message broadcasts
  assets/css/app.css
  assets/js/hooks.js
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: C4GT Community

#2930 Delete contact field optionally with contact data
  lib/glific/flows/contact_field.ex
  lib/glific_web/resolvers/contacts_field.ex
  lib/glific_web/schema/contacts_field_type.ex
  test/glific/contacts_field_test.exs
Labels: enhancement

#2923 add bar chart to demonstrate the most active time of the chatbot
  assets/js/hooks.js
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: C4GT Community

#2959 Lets try to minimize flaky tests
  .github/workflows/continuous-integration.yml
  .tool-versions
  elixir_buildpack.config
  lib/glific/providers/gupshup/partner/partner_api.ex
  mix.exs
  test/glific/access_control_test.exs
  test/glific/contacts_test.exs
  test/glific/flows_test.exs
  test/glific/messages_test.exs
  test/glific_web/schema/api/router_test.exs
  test/glific_web/schema/contact_group_test.exs
  test/glific_web/schema/credential_test.exs
  test/glific_web/schema/export_test.exs
  test/glific_web/schema/flow_test.exs
  test/glific_web/schema/group_test.exs
  test/glific_web/schema/language_test.exs
  test/glific_web/schema/message_test.exs
  test/glific_web/schema/notification_test.exs
  test/glific_web/schema/organization_test.exs
  test/glific_web/schema/provider_test.exs
Labels: enhancement
