Repository glific/glific, pull requests merged in 2023-12, with the labels that each got.

#3243 Email: Updating support mail group
  lib/glific/communications/mailer.ex
  lib/glific/mails/report_gupshup_mail.ex
Labels: enhancement

#3245 Update README with suggested edits
  README.md
Labels: documentation

#3246 Flows: Language Alert
  lib/glific/flows/flow.ex
  priv/data/flows/test.json
  test/glific/flows_test.exs
Labels: enhancement

#3248 Flow: Next node after interactive should be wait for response
  lib/glific/flows/action.ex
  test/glific/flows_test.exs
Labels: ready for review

#3255 Ticketing system: add the body filter in tickets
  lib/glific/tickets.ex
  lib/glific_web/schema/ticket_types.ex
  test/glific_web/schema/ticket_test.exs
Labels: ready for review

#3247 Automated flow tester: Trigger should starting with an hsm template
  lib/glific/triggers.ex
  test/glific/access_control_test.exs
  test/glific/triggers_test.exs
  test/glific_web/schema/trigger_test.exs
  test/support/fixtures.ex
Labels: ready for review

#3261 Bug: Template-translation
  lib/glific/flows/flow.ex
  lib/glific/settings.ex
  test/glific/flows_test.exs
Labels: bug

#3254 Ticketing System: export tickets
  lib/glific/tickets.ex
  test/glific_web/schema/ticket_test.exs
Labels: ready for review

#3269 Client: KEF GCS structure
  lib/glific/clients/kef.ex
Labels: consulting

#3274 Flows: hotfix for few issues
  lib/glific/flows/flow.ex
  lib/glific/triggers.ex
Labels: bug
