Repository glific/glific, pull requests merged in 2023-09, with the labels that each got.

#3063 Trigger: Adding few more testcases
  assets/gql/triggers/fields.frag.gql
  lib/glific/communications/mailer.ex
  lib/glific/triggers.ex
  lib/glific_web/schema/trigger_types.ex
  test/glific_web/schema/trigger_test.exs
Labels: enhancement

#3065 Internal Dashboard: UI Fixes
  assets/css/app.css
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: ready for review, C4GT Community

#3064 Trigger and Tracker: Test cases
  coveralls.json
  lib/glific_web/templates/live/stats_live.html.heex
  test/glific/tracker_test.exs
  test/glific/triggers_test.exs
Labels: ready for review

#3074 Common Webhook: Openllm
  lib/glific/clients/common_webhook.ex
Labels: enhancement

#3055 Internal Dashboard: Support for Dashboard Links
  lib/glific/partners/setting.ex
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
  test/glific/reports_test.exs
Labels: ready for review

#3085 Message Media: Table optimizations
  lib/glific/messages/message_media.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific_web/schema/message_media_types.ex
  priv/repo/migrations/20230909123216_add_is_template_media_to_messages_media.exs
  test/glific/communications_test.exs
  test/glific/messages_test.exs
  test/support/fixtures.ex
Labels: enhancement

#3062 Template: Syncing Updated UUID
  lib/glific/templates.ex
  test/glific/templates_test.exs
Labels: ready for review

#3081 Role:Provide access to staff
  lib/glific_web/schema/ticket_types.ex
  lib/glific_web/schema/users_types.ex
Labels: ready for review

#3079 Audit: Enhancing Password Policy
  lib/glific/saas/queries.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific/seeds/seeds_migration.ex
  lib/glific/users/user.ex
  mix.exs
  mix.lock
  priv/repo/seeds/20200723172939_add_glific_data.exs
  test/glific/users_test.exs
  test/glific_web/flows/flow_editor_controller_test.exs
  test/glific_web/registration_controller_test.exs
  test/glific_web/schema/api/router_test.exs
  test/glific_web/session_controller_test.exs
  test/k6/helpers.js
  test/support/fixtures.ex
  test/support/fixtures/accounts_fixtures.ex
Labels: enhancement

#3092 Templates: sync fixes
  lib/glific/templates.ex
Labels: bug

#3101 Authorize: Bugfixes
  lib/glific/reports.ex
  lib/glific_web/schema/middleware/authorize.ex
  lib/glific_web/templates/live/stats_live.html.heex
  test/glific_web/schema/user_test.exs
Labels: bug

#3095 Internal Dashboard: Tidy up bar chart labels to prevent clutter
  lib/glific_web/templates/live/stats_live.ex
Labels: ready for review, C4GT Community

#3117 Audit: Restricting Cookies
  lib/glific_web/endpoint.ex
  lib/glific_web/templates/live/stats_live.ex
Labels: enhancement

#3113 Fix support for the Mail on all clients
  lib/glific/reports.ex
  lib/glific/stats.ex
  lib/glific_web/templates/dashboard/dashboard.html.heex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/views/dashboard_view.ex
  mix.exs
  mix.lock
Labels: ready for review

#3024 Default sort of flows page
  lib/glific/flows.ex
  lib/glific_web/schema/middleware/safe_resolution.ex
Labels: enhancement

#3108 User:Last login time
  lib/glific_web/controllers/api/v1/session_controller.ex
  test/glific_web/session_controller_test.exs
Labels: ready for review

#3121 #3056 -error handling for the empty expression
  lib/glific/flows/templating.ex
Labels: ready for review

#3129 Flows: flow listing bug
  lib/glific/flows.ex
  test/glific/flows_test.exs
Labels: bug

#3131 Audit: active user sessions
  lib/glific/users.ex
  lib/glific_web/plugs/api_auth_plug.ex
  lib/glific_web/resolvers/users.ex
  lib/glific_web/schema/users_types.ex
  test/glific_web/api_auth_plug_test.exs
Labels: enhancement, audit

#3128 Flows:Warning Categorizations
  lib/glific/flows.ex
  lib/glific/flows/action.ex
  lib/glific/flows/case.ex
  lib/glific/flows/flow.ex
  lib/glific/flows/wait.ex
  lib/glific_web/schema/flow_types.ex
Labels: ready for review
