Repository glific/glific, pull requests merged in 2023-08, with the labels that each got.

#2974 Bhasini integration
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/asr/bhasini.ex
Labels: ready for review

#2980 Bug: removing tag dependency
  lib/glific/processor/consumer_tagger.ex
  test/glific/processor/consumer_tagger_test.exs
Labels: bug

#2969 conversations from stats table
  lib/glific/reports.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific/stats.ex
  lib/glific/stats/stat.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific_web/templates/live/stats_live.ex
  priv/repo/migrations/20230801091505_stats_add_conversations_column.exs
Labels: C4GT Community

#2984 Lahi extension update for the bhasini
  lib/glific/clients/lahi.ex
Labels: ready for review

#2953 Client: KEF new GCS structure
  lib/glific/clients/kef.ex
Labels: consulting

#2991 Flows: Active profile id at flow level
  lib/glific/contacts.ex
  priv/data/flows/completion.json
Labels: enhancement

#2951 Internal Dashboard: Export function for opted in, opted out and non-opted contacts
  assets/css/app.css
  assets/js/hooks.js
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: C4GT Community

#3006 Most Active Hour in ContEx
  assets/css/app.css
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: ready for review

#3012 Notifications: Sending Warning Mails
  lib/glific/mails/critical_notification_mail.ex
  lib/glific/mails/notification_mail.ex
  lib/glific/notifications.ex
  test/glific/communications_test.exs
  test/glific/notifications_test.exs
Labels: ready for review

#3003 Dashboard mail
  lib/glific/communications/mailer.ex
  lib/glific/mails/dashboard_mail.ex
  lib/glific/reports.ex
  lib/glific/stats.ex
  lib/glific_web/templates/dashboard/dashboard.html.heex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/views/dashboard_view.ex
  test/glific/reports_test.exs
  test/glific/stats_test.exs
Labels: ready for review

#3021 Increase api timeout for Bhasini
  lib/glific/third_party/asr/bhasini.ex
Labels: ready for review, consulting

#3026 Client: Bandhu Webhook
  lib/glific/clients/bandhu.ex
Labels: consulting

#3014 Triggers: Updating Group IDs
  lib/glific/flows/broadcast.ex
  lib/glific/flows/broadcast/message_broadcast.ex
  lib/glific/flows/flow.ex
  lib/glific/third_party/asr/bhasini.ex
  lib/glific/triggers.ex
  lib/glific/triggers/trigger.ex
  lib/glific_web/schema/flow_types.ex
  lib/glific_web/schema/trigger_types.ex
  priv/repo/migrations/20230814065215_add_group_ids_and_description_column.exs
  test/glific_web/schema/flow_test.exs
Labels: ready for review

#3031 Bandhu: WB fixes
  lib/glific/clients/bandhu.ex
Labels: consulting

#3025 Internal Dashboard: Send dashboard mail on DAILY/WEEKLY/MONTHLY basis
  config/config.exs
  lib/glific/jobs/minute_worker.ex
  lib/glific/partners.ex
  priv/repo/migrations/20230803115906_add_columns_in_organization.exs
  test/glific/partners/partners_test.exs
Labels: ready for review

#3041 Client/bandhu wb fixes
  lib/glific/clients/bandhu.ex
Labels: consulting

#3049 Dashboard bug fixes
  lib/glific/reports.ex
Labels: ready for review

#3043 Run default or out of office flow each time
  lib/glific/flows/periodic.ex
  lib/glific/notifications.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific/partners/out_of_office.ex
  lib/glific/partners/setting.ex
  lib/glific/providers/balance_worker.ex
  lib/glific_web/schema/organization_types.ex
  lib/glific_web/templates/live/stats_live.ex
  test/glific/partners/partners_test.exs
Labels: ready for review

#3051 Webhook changes for sheet interactive
  lib/glific/clients/common_webhook.ex
Labels: ready for review

#3044 flows:long-response-warning
  lib/glific/flows/action.ex
  lib/glific/flows/wait.ex
  priv/data/flows/test.json
  test/glific/flows_test.exs
Labels: ready for review

#3036 Internal Dashbord: Seeding Dev
  assets/css/app.css
  lib/glific/seeds/seeds_dev.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: enhancement

#3060 Internal Dashboard: Quickfixes
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
Labels: enhancement

#3042 sending multiple
  lib/glific/communications/mailer.ex
  lib/glific/partners/organization.ex
Labels: ready for review
