Repository glific/glific, pull requests merged in 2024-04, with the labels that each got.

#3472 WA Groups: Exclude dms and collection msgs fom wa_search_multi
  lib/glific/searches.ex
  test/glific/searches_test.exs
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
  test/glific_web/schema/search_test.exs
Labels: bug

#3481 Client: KEF GCS Error
  lib/glific/clients/kef.ex
Labels: bug

#3484 Flow Context: Added validations in flow context for contact_id and wa_group_id
  lib/glific/flows/flow_context.ex
  test/glific/flows/flow_context_test.exs
Labels: ready for review

#3488 BugFix: OTP Template
  lib/glific/messages.ex
Labels: bug

#3475 Removed support for sending ogg audio in WABA
  lib/glific/messages.ex
  test/glific/messages_test.exs
Labels: ready for review

#3495 WA group: error handling in wa group collection
  lib/glific/providers/maytapi/message.ex
  test/glific/groups/whatsapp_message_test.exs
Labels: ready for review

#3496 Bigquery: Schema Changes
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: bug

#3501 GCS Worker: Handling account not found error
  lib/glific/partners.ex
  test/glific/gcs_worker_test.exs
Labels: ready for review

#3498 WABA collection: Handle the error when group_is is empty list
  lib/glific/flows.ex
  lib/glific/flows/broadcast.ex
  test/glific/flows_test.exs
  test/glific_web/schema/flow_test.exs
Labels: ready for review

#3499 Metrics: Autotranslate & WA Group
  lib/glific/flows/translate/translate.ex
  lib/glific/providers/maytapi/api_client.ex
  lib/glific_web/providers/maytapi/shunt.ex
  lib/glific_web/resolvers/flows.ex
Labels: enhancement

#3486 Contacts: Added validation in `fields` in contacts table
  lib/glific/contacts/contact.ex
  test/glific/contacts_test.exs
Labels: ready for review

#3503 BQ: sending specific error message incase of error
  lib/glific/third_party/bigquery/bigquery.ex
Labels: enhancement

#3504 Appsignal: log undefined action node error
  lib/glific/flows/action.ex
  test/glific/flows/action_test.exs
Labels: ready for review

#3523 WA Groups: Group Collections: Added Search for groups inside a group collection
  lib/glific/groups/wa_groups.ex
  lib/glific_web/schema/wa_group_types.ex
  test/glific_web/schema/wa_group_collection_test.exs
Labels: ready for review

#3525 Revert "Bigquery: Schema Changes"
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: bug

#3512 Open LLM: API Updates
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/open_llm/openLLM.ex
Labels: enhancement

#3520 Fetch user profiles: handling results map structure in webhook function
  lib/glific/clients/bandhu.ex
  test/glific/clients_test.exs
Labels: ready for review

#3526 OpenLLM: MVP
  assets/gql/organizations/get_services.gql
  lib/glific/clients/common_webhook.ex
  lib/glific/misc/flags.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific/third_party/llm4dev/llm4dev.ex
  lib/glific/third_party/open_llm/openLLM.ex
  lib/glific_web/resolvers/llm4dev.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/llm4dev_types.ex
  lib/glific_web/schema/organization_types.ex
  priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs
  test/glific_web/schema/organization_test.exs
Labels: enhancement

#3533 Gupshup: API URL changes
  lib/glific/providers/gupshup/api_client.ex
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific/providers/gupshup/worker.ex
  lib/glific/saas/queries.ex
Labels: enhancement

#3535 GPT: added support for GPT vision
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/openAI/chatGPT.ex
Labels: enhancement
