Repository glific/glific, pull requests merged in 2024-10, with the labels that each got.

#3842 ERP next: fetch the list of orgs from ERP
  api.docs/bruno/glific_api/SaaS/Fetch ERP organizations.bru
  config/.env.dev.txt
  config/runtime.exs
  lib/glific/erp.ex
  lib/glific/registrations/registration.ex
  lib/glific/saas/onboard.ex
  lib/glific/saas/queries.ex
  lib/glific_web/controllers/api/v1/onboard_controller.ex
  lib/glific_web/router.ex
  priv/repo/migrations/20240930061155_add_fields_in_term_and_cond.exs
  test/glific/erp_test.exs
  test/glific/partners/onboard_test.exs
Labels: ready for review

#3846 Contact Import: fetching pending user_jobs by skipping org id
  lib/glific/jobs/user_jobs.ex
Labels: ready for review

#3836 Template Flows: Triggering flow for simulators
  lib/glific/flows.ex
  lib/glific/processor/consumer_flow.ex
  lib/glific/processor/consumer_tagger.ex
  test/glific/processor/consumer_flow_test.exs
Labels: enhancement

#3855 Flows: List flows
  lib/glific/flows.ex
  lib/glific/third_party/openAI/chatGPT.ex
  test/glific/flows_test.exs
  test/glific_web/schema/flow_test.exs
Labels: bug

#3858 Bhasini: Support Longer audios
  lib/glific/third_party/asr/bhasini.ex
Labels: enhancement

#3724 Internal Dashboard: Bigquery Sync status
  lib/glific/reports.ex
  lib/glific_web/templates/live/stats_live.ex
  lib/glific_web/templates/live/stats_live.html.heex
Labels: enhancement

#3866 Calendar: Using org Timezone
  lib/glific/flows/message_vars_parser.ex
  test/glific/flows/message_vars_parser_test.exs
Labels: enhancement
