Repository glific/glific, pull requests merged in 2024-05, with the labels that each got.

#3540 T&C: update-registration-details and reachout api
  api.docs/bruno/glific_api/SaaS/Create an organization- organization contact and BSP credentials.bru
  api.docs/bruno/glific_api/SaaS/Reachout to support.bru
  api.docs/bruno/glific_api/SaaS/Update registration details.bru
  lib/glific/registrations.ex
  lib/glific/registrations/registration.ex
  lib/glific/saas/onboard.ex
  lib/glific/saas/queries.ex
  lib/glific_web/controllers/api/v1/onboard_controller.ex
  lib/glific_web/router.ex
  priv/repo/migrations/20240424071508_add_terms_and_cond.exs
  test/glific/partners/onboard_test.exs
Labels: ready for review

#3543 flow: broadcast flow to group when group is not found
  lib/glific/flows/broadcast.ex
  test/glific_web/schema/flow_test.exs
Labels: ready for review

#3551 GPT Enhancement and logs
  lib/glific/clients/common_webhook.ex
  lib/glific/clients/kef.ex
  lib/glific/clients/udhyam.ex
  lib/glific/third_party/openAI/chatGPT.ex
Labels: enhancement

#3561 Generic error message
  lib/glific_web/schema/middleware/safe_resolution.ex
  test/glific/partners/partners_test.exs
  test/glific/processor/consumer_flow_test.exs
Labels: enhancement

#3562 Bigquery: Syncing schema Error
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: bug

#3564 GPT: Enhancements
  lib/glific/third_party/openAI/chatGPT.ex
Labels: enhancement

#3546 T&C: onboard and reachout api
  api.docs/bruno/glific_api/SaaS/Create an organization- organization contact and BSP credentials.bru
  api.docs/bruno/glific_api/SaaS/Reachout to support.bru
  api.docs/bruno/glific_api/SaaS/Update registration details.bru
  api.docs/bruno/glific_api/environments/dev.bru
  lib/glific/communications/mailer.ex
  lib/glific/mails/new_partner_onboarded_mail.ex
  lib/glific/partners/organization.ex
  lib/glific/providers/gupshup/contacts.ex
  lib/glific/registrations.ex
  lib/glific/registrations/registration.ex
  lib/glific/saas/onboard.ex
  lib/glific/saas/queries.ex
  lib/glific/third_party/gcs/gcs_worker.ex
  lib/glific_web/controllers/api/v1/onboard_controller.ex
  lib/glific_web/router.ex
  priv/repo/migrations/20240424071508_add_terms_and_cond.exs
  priv/repo/seeds/20200723172939_add_glific_data.exs
  test/glific/groups/whatsapp_group_test.exs
  test/glific/partners/onboard_test.exs
Labels: ready for review

#3565 T&C: Sync to Notion
  config/.env.dev.txt
  config/runtime.exs
  lib/glific/notion.ex
  lib/glific/registrations/registration.ex
  lib/glific/saas/onboard.ex
  lib/glific/saas/queries.ex
  priv/repo/migrations/20240424071508_add_terms_and_cond.exs
  test/glific/notion_test.exs
  test/glific/partners/onboard_test.exs
  test/support/fixtures.ex
Labels: ready for review

#3573 Organization: Added forced_suspension status
  lib/glific/clients/reap_benefit.ex
  lib/glific/enums/constants/enums.ex
  lib/glific/saas/onboard.ex
  priv/repo/migrations/20240527105105_add_forced_suspension_enum.exs
  test/glific/partners/onboard_test.exs
Labels: enhancement

#3576 FunWithFlags: Using separate pipe in router
  lib/glific_web/router.ex
Labels: ready for review
