Repository glific/glific, pull requests merged in 2024-01, with the labels that each got.

#3268 Trigger: show waning when the flow in trigger starts with no hsm template
  assets/gql/triggers/validate.gql
  lib/glific/triggers.ex
  lib/glific_web/resolvers/triggers.ex
  lib/glific_web/schema/trigger_types.ex
  test/glific/triggers_test.exs
  test/glific_web/schema/trigger_test.exs
Labels: ready for review

#3278 Organization:populate data in org table
  lib/glific/saas/queries.ex
Labels: ready for review

#3282 Auto Translate: Feature Flag
  assets/gql/organizations/get_services.gql
  lib/glific/misc/flags.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific_web/schema/organization_types.ex
  test/glific_web/schema/organization_test.exs
Labels: enhancement

#3279 Fix & Update Setup Instructions in README.md
  README.md
Labels: documentation

#3287 Auto Translate: Bugfixes
  lib/glific/flows/translate/open_ai.ex
  test/glific/flows/translate/open_ai_test.exs
Labels: bug

#3284 Organization: Settings
  lib/glific_web/schema/organization_types.ex
Labels: enhancement

#3293 Bruno: Update setup steps
  api.docs/bruno/setup.md
Labels: documentation

#3294 Auto Translate: Parallel Translation
  lib/glific/flows/translate/open_ai.ex
  test/glific/flows/translate/open_ai_test.exs
Labels: enhancement

#3300 Organization: Updating API
  lib/glific/misc/flags.ex
  lib/glific_web/schema/organization_types.ex
Labels: enhancement

#3301 Auto Translate: Parallel Translation at lang level
  lib/glific/flows/translate/export.ex
  lib/glific/flows/translate/open_ai.ex
Labels: enhancement

#3299 Partner API: Setting Callback URL
  lib/glific/providers/gupshup/partner/partner_api.ex
  test/glific/partners/partners_test.exs
Labels: enhancement

#3302 Auto Translate: Export without translation
  lib/glific/flows/translate/export.ex
  lib/glific_web/resolvers/flows.ex
  lib/glific_web/schema/flow_types.ex
Labels: enhancement

#3298 Auto Translate: Integrate Google Translate
  config/.env.dev.txt
  lib/glific.ex
  lib/glific/flows/translate/google_translate.ex
  lib/glific/flows/translate/open_ai.ex
  lib/glific/flows/translate/translate.ex
  lib/glific/third_party/google_translate/translate.ex
  mix.exs
  mix.lock
  test/glific/flows/translate/google_translate_test.exs
Labels: ready for review

#3305 Partner API: Business Profile
  lib/glific/providers/gupshup/partner/partner_api.ex
  test/glific/partners/partners_test.exs
Labels: enhancement
