Repository glific/glific, pull requests merged in 2024-02, with the labels that each got.

#3324 Automated flow tester: Show Node UUID
  lib/glific/flows/flow.ex
  test/glific/flows_test.exs
Labels: enhancement

#3325 Enhancement/node template translation warning
  lib/glific/flows/flow.ex
Labels: bug

#3312 API Documentation
  api.docs/bruno/glific_api/Authentication/Create a new session for an existing user.bru
  api.docs/bruno/glific_api/Authentication/Create a new user.bru
  api.docs/bruno/glific_api/Authentication/Login.bru
  api.docs/bruno/glific_api/Authentication/Renew an existing session.bru
  api.docs/bruno/glific_api/Authentication/Reset Password.bru
  api.docs/bruno/glific_api/Authentication/Send an OTP request to verify a phone number of existing user.bru
  api.docs/bruno/glific_api/Authentication/Send an OTP request to verify a phone number.bru
  api.docs/bruno/glific_api/Contact Group/Create Contact Group.bru
  api.docs/bruno/glific_api/Contact Group/Update a Group with contacts to be added and contacts to be deleted.bru
  api.docs/bruno/glific_api/Contact Group/Update groups to be added and groups to be deleted to a Contact.bru
  api.docs/bruno/glific_api/Contact Tag/Create Contact Tag.bru
  api.docs/bruno/glific_api/Contact Tag/Subscription for Create Contact Tag.bru
  api.docs/bruno/glific_api/Contact Tag/Subscription for Delete Contact Tag.bru
  api.docs/bruno/glific_api/Contact Tag/Update a Contact with tags to be added and tags to be deleted.bru
  api.docs/bruno/glific_api/Contacts/Block a Contacts.bru
  api.docs/bruno/glific_api/Contacts/Get All Contacts.bru
Labels: documentation

#3336 Automated flow tester: Deleted node template translation warning
  lib/glific/flows/flow.ex
Labels: bug

#3317 Auto translate: Enable the feature flag for google translate
  lib/glific/flows/translate/export.ex
  lib/glific/flows/translate/google_translate.ex
  lib/glific/flows/translate/translate.ex
  lib/glific/misc/flags.ex
  lib/glific/partners.ex
  lib/glific/third_party/google_translate/translate.ex
  test/glific/flows/translate/open_ai_test.exs
Labels: ready for review

#3354 Internal Dashboard: Filtering out default contacts from stats
  lib/glific/reports.ex
Labels: enhancement

#3350 Organization: Updating API response
  lib/glific/partners.ex
  lib/glific_web/resolvers/partners.ex
Labels: enhancement

#3353 Auto translate: Cleanups
  lib/glific/flows/translate/google_translate.ex
  lib/glific/flows/translate/translate.ex
  lib/glific/misc/flags.ex
  lib/glific/partners.ex
  lib/glific/settings.ex
Labels: enhancement

#3359 Auto translate: Fix default language order
  lib/glific/flows/translate/export.ex
Labels: bug

#3368 WA Groups: Callback optimizations
  lib/glific/groups/whatsapp_group.ex
  lib/glific/partners.ex
  lib/glific/providers/maytapi/api_client.ex
  lib/glific/wa_group/wa_managed_phone.ex
  lib/glific/wa_managed_phones.ex
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs
  test/glific/groups/whatsapp_group_test.exs
  test/glific/wa_managed_phones_test.exs
  test/support/fixtures/wa_groups_fixtures.ex
Labels: enhancement

#3370 WA Groups: Group info
  lib/glific/groups/group.ex
  lib/glific/groups/whatsapp_group.ex
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  test/glific/groups/whatsapp_group_test.exs
  test/support/fixtures/wa_groups_fixtures.ex
Labels: enhancement

#3357 WA groups: Add support to receive text message from groups
  lib/glific/communications/message.ex
  lib/glific/contacts.ex
  lib/glific/groups/whatsapp_group.ex
  lib/glific_web/providers/maytapi/controller/message_controller.ex
  test/glific/groups/whatsapp_group_test.exs
  test/glific/wa_managed_phones_test.exs
  test/glific_web/providers/gupshup/controllers/message_controller_test.exs
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
  test/support/fixtures/wa_groups_fixtures.ex
Labels: ready for review

#3338 Ngrok doc: Added phno and msg details to start working with WA bot
  README.md
Labels: ready for review

#3375 WA groups: creates a group, if group for receiving message doesn't exist
  lib/glific/communications/message.ex
  lib/glific/groups.ex
  lib/glific_web/providers/maytapi/controller/message_controller.ex
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
Labels: ready for review

#3372 WA groups: Add support to receive media message from groups
  lib/glific/communications/message.ex
  lib/glific/providers/maytapi/message.ex
  lib/glific_web/providers/maytapi/controller/message_controller.ex
  lib/glific_web/providers/maytapi/router.ex
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
Labels: ready for review

#3381 WA groups: enable the feature flag
  assets/gql/organizations/get_services.gql
  lib/glific/misc/flags.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific_web/schema/organization_types.ex
  test/glific_web/schema/organization_test.exs
Labels: ready for review

#3382 WA Group: Schema changes
  .formatter.exs
  lib/glific/communications/message.ex
  lib/glific/groups.ex
  lib/glific/groups/group.ex
  lib/glific/groups/wa_group.ex
  lib/glific/groups/wa_groups.ex
  lib/glific/groups/whatsapp_group.ex
  lib/glific/messages/message.ex
  lib/glific/partners.ex
  lib/glific/wa_group/wa_managed_phone.ex
  lib/glific/wa_managed_phones.ex
  priv/repo/migrations/20230814065215_add_group_ids_and_description_column.exs
  priv/repo/migrations/20230818012026_add_indexes.exs
  priv/repo/migrations/20231118000016_upgrade_oban_16.exs
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs
  test/glific/groups/whatsapp_group_test.exs
  test/glific/wa_managed_phones_test.exs
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
  test/support/fixtures/wa_groups_fixtures.ex
Labels: enhancement

#3389 WA Groups: Updated receiving messages with new schema changes
  lib/glific/communications/message.ex
  lib/glific/contacts.ex
  lib/glific/providers/maytapi/message.ex
  lib/glific/wa_group/wa_message.ex
  lib/glific_web/providers/maytapi/controller/message_controller.ex
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  test/glific/groups/whatsapp_message_test.exs
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
Labels: ready for review

#3390 WA Groups: creating contact for wa_managed_phone and updating on receiving messages
  lib/glific/communications/message.ex
  lib/glific/wa_group/wa_managed_phone.ex
  lib/glific/wa_managed_phones.ex
  lib/glific_web/providers/maytapi/controller/message_controller.ex
  lib/glific_web/providers/maytapi/shunt.ex
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  test/glific/wa_managed_phones_test.exs
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
  test/support/fixtures/wa_groups_fixtures.ex
Labels: ready for review

#3371 WA groups: send message in wa groups
  assets/gql/messages/wa_group_message.gql
  config/config.exs
  lib/glific/communications/wa_group_message.ex
  lib/glific/providers/gupshup/message.ex
  lib/glific/providers/maytapi/api_client.ex
  lib/glific/providers/maytapi/message.ex
  lib/glific/providers/maytapi/response_handler.ex
  lib/glific/providers/maytapi/wa_messages.ex
  lib/glific/providers/maytapi/wa_worker.ex
  lib/glific/wa_group/wa_message.ex
  lib/glific/wa_messages.ex
  lib/glific_web/resolvers/messages.ex
  lib/glific_web/schema/message_types.ex
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  test/glific/groups/whatsapp_message_test.exs
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
  test/glific_web/schema/wa_message_test.exs
  test/support/fixtures/wa_groups_fixtures.ex
Labels: ready for review

#3393 WA Group: Trigger and APIs for wa_managed_phone
  assets/gql/wa_managed_phones/count.gql
  assets/gql/wa_managed_phones/list.gql
  lib/glific/wa_managed_phones.ex
  lib/glific_web/resolvers/wa_managed_phones.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/wa_managed_phone_type.ex
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  priv/repo/migrations/20240222064744_add_trigger_for_wa_message_number.exs
  test/glific_web/schema/wa_managed_phone.exs
Labels: enhancement

#3316 Gupshup: fix the email values format
  lib/glific/templates.ex
Labels: ready for review

#3396 WA group: send media in wa group
  lib/glific/communications/wa_group_message.ex
  lib/glific/providers/maytapi/message.ex
  lib/glific/providers/maytapi/wa_messages.ex
  lib/glific/templates.ex
  lib/glific_web/schema/message_types.ex
  test/glific/groups/whatsapp_message_test.exs
Labels: ready for review

#3400 WA Group: Subscriptions
  lib/glific/communications/message.ex
  lib/glific/communications/wa_group_message.ex
  lib/glific_web/schema/message_types.ex
Labels: enhancement
