Repository glific/glific, pull requests merged in 2024-06, with the labels that each got.

#3583 Clients: Common functions issue
  lib/glific/clients.ex
  lib/glific/clients/arogya_world.ex
  lib/glific/clients/avanti.ex
  lib/glific/clients/balajanaagraha.ex
  lib/glific/clients/bharat_rohan.ex
  lib/glific/clients/digital_green.ex
  lib/glific/clients/digital_green_jharkhand.ex
  lib/glific/clients/kef.ex
  lib/glific/clients/mukkamaar.ex
  lib/glific/clients/oblf.ex
  lib/glific/clients/pehlay_akshar.ex
  lib/glific/clients/quest_alliance.ex
  lib/glific/clients/reap_benefit.ex
  lib/glific/clients/sol.ex
  lib/glific/clients/stir.ex
  lib/glific/clients/suno_sunao.ex
  lib/glific/clients/tap.ex
  lib/glific/clients/udhyam.ex
  test/glific/clients_test.exs
Labels: bug

#3587 Messaging: Group message warning
  assets/gql/contact_groups/count.gql
  lib/glific/groups/contact_groups.ex
  lib/glific_web/resolvers/groups.ex
  lib/glific_web/resolvers/messages.ex
  lib/glific_web/schema/contact_group_types.ex
  test/glific_web/schema/contact_group_test.exs
Labels: bug

#3589 Tickets: Flow ID
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific/tickets.ex
  lib/glific/tickets/ticket.ex
  priv/repo/migrations/20240605165834_add_flow_id.exs
  test/glific_web/schema/ticket_test.exs
  test/support/fixtures/tickets_fixtures.ex
Labels: enhancement

#3586 Clearing some default flow labels and contact fields
  priv/repo/seeds/20200723172939_add_glific_data.exs
  test/glific_web/schema/flow_label_test.exs
Labels: ready for review

#3590 Auto Translate fixes
  .github/workflows/continuous-integration.yml
  lib/glific/contacts/import.ex
  lib/glific/providers/gupshup/template.ex
  lib/glific/providers/gupshup_enterprise/template.ex
  lib/glific/third_party/google_translate/translate.ex
  lib/glific/third_party/sheets/api_client.ex
  lib/glific_web/resolvers/flows.ex
  mix.exs
  mix.lock
  test/glific/templates_test.exs
Labels: ready for review

#3584 Org status in session response and org status check on login
  lib/glific/partners/organization.ex
  lib/glific_web/controllers/api/v1/session_controller.ex
  test/glific/partners/onboard_test.exs
  test/glific_web/session_controller_test.exs
Labels: ready for review

#3595 Node number warning
  lib/glific/flows/action.ex
  test/glific/flows_test.exs
Labels: enhancement

#3572 Flows: export flow not working
  lib/glific/flows.ex
  lib/glific_web/resolvers/flows.ex
  lib/glific_web/schema/flow_types.ex
  test/glific_web/schema/flow_test.exs
Labels: ready for review

#3468 WA Groups: Setting maytapi webhook api for org
  lib/glific/flows/action.ex
  lib/glific/groups/wa_groups.ex
  lib/glific/partners.ex
  lib/glific/providers/maytapi/api_client.ex
  test/glific/groups/whatsapp_group_test.exs
Labels: ready for review

#3601 Bhasini
  config/.env.dev.txt
  config/.env.test
  config/releases.exs.txt
  config/runtime.exs
  lib/glific.ex
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/asr/bhasini.ex
  lib/glific/third_party/bhasini/bhasini.ex
Labels: enhancement

#3578 Auto translation: Enable translation for interactive msg
  lib/glific/templates/interactive_templates.ex
  lib/glific_web/resolvers/interactives.ex
  lib/glific_web/schema/interactive_template_types.ex
  test/glific/interactive_templates_test.exs
Labels: ready for review

#3598 allowTemplateChange
  assets/gql/session_templates/fields.frag.gql
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific/providers/gupshup/template.ex
  lib/glific/templates/session_templates.ex
  lib/glific_web/schema/session_template_type.ex
  test/glific/templates_test.exs
  test/glific_web/schema/session_template_test.exs
Labels: ready for review

#3609 Returning conn on errors when sending otp
  lib/glific_web/controllers/api/v1/registration_controller.ex
  test/glific_web/registration_controller_test.exs
  test/glific_web/schema/wa_search_test.exs
Labels: ready for review

#3602 Auto trans/export import
  lib/glific/templates/interactive_templates.ex
  lib/glific_web/resolvers/interactives.ex
  lib/glific_web/schema/interactive_template_types.ex
  test/glific/interactive_templates_test.exs
Labels: ready for review

#3620 Notification mails: Using org name and email as `to` email address instead of empty list
  lib/glific/mails/notification_mail.ex
Labels: ready for review

#3610 Bhasini integration: NMT & TTS
  lib/glific/clients/common_webhook.ex
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific/third_party/asr/bhasini.ex
  lib/glific/third_party/bhasini/bhasini.ex
  lib/glific_web/resolvers/interactives.ex
  test/glific_web/schema/session_template_test.exs
Labels: enhancement

#3622 Not sending `unexpected message received on wait_for_time` error explicitly to appsignal
  lib/glific.ex
Labels: ready for review

#3627 Bigquery: Added check for nil flow
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: bug

#3630 Bhasini: translated text
  lib/glific/third_party/bhasini/bhasini.ex
Labels: enhancement

#3615 Interactive message: import translation from csv
  lib/glific/templates.ex
  lib/glific/templates/interactive_templates.ex
  lib/glific_web/resolvers/interactives.ex
  lib/glific_web/schema/interactive_template_types.ex
  test/glific/interactive_templates_test.exs
  test/glific/templates_test.exs
Labels: ready for review

#3639 Flows: parsing result category
  lib/glific/flows/action.ex
  test/glific/flows/action_test.exs
Labels: bug

#3607 Contacts: added exclude groups
  lib/glific/contacts.ex
  lib/glific/groups/wa_groups.ex
  lib/glific_web/schema/contact_types.ex
  lib/glific_web/schema/wa_group_types.ex
  test/glific_web/schema/contact_test.exs
Labels: enhancement

#3599 WA Groups: MessageEventController response time reduced by running inside a Task
  lib/glific_web/providers/maytapi/controller/message_event_controller.ex
  test/glific_web/schema/wa_message_test.exs
  test/glific_web/schema/wa_search_test.exs
Labels: ready for review
