Repository glific/glific, pull requests merged in 2024-09, with the labels that each got.

#3774 Contact Import: Downloading reports works even if there are no errors in the upload process
  assets/gql/contacts/upload_report.gql
  lib/glific/contacts/import.ex
  test/glific/contacts_test.exs
  test/glific_web/schema/contact_test.exs
Labels: ready for review

#3767 openAI: Support for json responses in vision and vanilla GPT functions
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/openAI/chatGPT.ex
  test/glific/flows/common_webhook_test.exs
  test/glific/flows/webhook_test.exs
Labels: enhancement, ready for review

#3782 OpenAI: Handling Thread ID
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/openAI/chatGPT.ex
  test/glific/third_party/openAI/chatGPT_test.exs
Labels: bug

#3783 HSM template: Fix button validation
  lib/glific/templates.ex
  test/glific/templates_test.exs
Labels: ready for review

#3785 OpenAI: Retry Mechanism
  lib/glific/third_party/openAI/chatGPT.ex
Labels: enhancement

#3786 Bug: Sending OpenAI response
  lib/glific/third_party/openAI/chatGPT.ex
Labels: bug

#3789 OpenAI: Webhook Error Cleanups
  lib/glific/third_party/openAI/chatGPT.ex
Labels: enhancement

#3781 BQ: sync contact groups table in BQ
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: ready for review

#3800 Bhasini: STT
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/bhasini/bhasini.ex
Labels: bug

#3802 Bhasini: cleanups
  lib/glific/clients/common_webhook.ex
  lib/glific/contacts.ex
  lib/glific/third_party/asr/bhasini.ex
Labels: bug

#3768 Interactive msg: validate the Interactive buttons
  lib/glific/templates/interactive_templates.ex
  test/glific/templates/interactive_template_test.exs
Labels: ready for review

#3771 Wa groups: storing the status of maytapi connected phone in Glific
  assets/gql/wa_managed_phones/list.gql
  lib/glific/wa_group/wa_managed_phone.ex
  lib/glific/wa_managed_phones.ex
  lib/glific_web/providers/maytapi/controller/status_controller.ex
  lib/glific_web/providers/maytapi/router.ex
  lib/glific_web/providers/maytapi/shunt.ex
  lib/glific_web/schema/wa_managed_phone_type.ex
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  test/glific/wa_managed_phones_test.exs
  test/glific_web/schema/wa_managed_phone_test.exs
  test/support/fixtures.ex
Labels: ready for review

#3803 BQ: Fix the group id column in contact groups
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: ready for review

#3797 Webhooks: Removed unique check for some urls
  lib/glific/flows/webhook.ex
  lib/glific/metrics.ex
  priv/repo/seeds/20200723172939_add_glific_data.exs
  test/glific/flows/webhook_test.exs
Labels: ready for review

#3794 Profile: update profile type and added testcases
  assets/gql/profiles/fields.frag.gql
  lib/glific_web/schema/profile_types.ex
  test/glific_web/schema/profile_test.exs
Labels: enhancement

#3793 KEF: New GCS media filepath structure
  lib/glific/clients/kef.ex
  test/glific/clients_test.exs
Labels: ready for review

#3814 Geolocation: Changes in the results variable
  lib/glific/clients/common_webhook.ex
  test/glific/flows/common_webhook_test.exs
Labels: enhancement

#3810 KEF file structure updates
  lib/glific/clients/kef.ex
  test/glific/clients_test.exs
Labels: enhancement

#3815 OpenAI : increasing timeout for all openai calls
  lib/glific/clients/kef.ex
  lib/glific/third_party/openAI/chatGPT.ex
Labels: bug

#3818 Bhasini: File conversion
  .github/workflows/continuous-deployment.yml
  build_scripts/gigalixir/ssh_profile.sh
  lib/glific/third_party/bhasini/bhasini.ex
  mix.exs
  test/glific/third_party/bhasini/bhasini_test.exs
Labels: bug

#3827 Deployment: Buildpacks Updates
  .buildpacks
  Aptfile
Labels: enhancement

#3760 Template flows: Adding the template flows in seeder
  lib/glific/seeds/seeds_flows.ex
  lib/glific/seeds/seeds_migration.ex
  priv/data/flows/GPT_Vision.json
  priv/data/flows/bhashini_text_to_speech.json
  priv/data/flows/bhasini_asr.json
  priv/data/flows/clear_variable.json
  priv/data/flows/consent_optin.json
  priv/data/flows/consent_optout.json
  priv/data/flows/direct_with_GPT.json
  priv/data/flows/filesearch_GPT_textandvoice.json
  priv/data/flows/geolocation.json
  priv/data/flows/other_options.json
  priv/data/flows/ticketing_help.json
Labels: ready for review

#3830 Template Flows: added logs for template flows
  lib/glific/flows.ex
  lib/glific/seeds/seeds_flows.ex
Labels: ready for review

#3829 Organisation: updating the suspension date after making the org active
  lib/glific/saas/onboard.ex
  test/glific/partners/onboard_test.exs
Labels: ready for review
