Repository glific/glific, pull requests merged in 2024-07, with the labels that each got.

#3625 GCS: enable logs for gcs bucket
  lib/glific/partners.ex
  lib/glific/third_party/gcs/gcs.ex
Labels: ready for review

#3658 Bhasini TTS: parsing contact language
  lib/glific/clients/common_webhook.ex
Labels: enhancement

#3660 Templates: generalising send template function
  lib/glific.ex
  lib/glific/clients/digital_green.ex
  lib/glific/clients/pehlay_akshar.ex
Labels: bug

#3661 OpenAI: GPT Citations
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/openAI/chatGPT.ex
  test/glific/third_party/openAI/chatGPT_test.exs
Labels: enhancement

#3659 Flows: Showing error message for nested flows during import
  lib/glific/flows.ex
  test/glific_web/schema/flow_test.exs
Labels: ready for review

#3667 Google sheets: fixed wrong csv export url
  lib/glific/third_party/sheets/sheets.ex
  test/support/fixtures.ex
Labels: bug

#3668 Flows: Optin Node updates
  priv/data/flows/help.json
  priv/data/flows/optin.json
  priv/repo/seeds/20200723172939_add_glific_data.exs
Labels: enhancement

#3690 Add metric for template flows
  lib/glific_web/resolvers/flows.ex
Labels: ready for review

#3693 GDPR: Masking phone numbers
  lib/glific.ex
  lib/glific/communications/message.ex
  lib/glific/communications/wa_group_message.ex
  lib/glific_web/controllers/api/v1/session_controller.ex
  lib/glific_web/providers/gupshup/controllers/user_event_controller.ex
  test/glific/glific_test.exs
Labels: enhancement
