Repository glific/glific, pull requests merged in 2024-08, with the labels that each got.

#3707 GPT: Voice to Voice
  lib/glific/clients/common_webhook.ex
Labels: enhancement

#3632 Partner API: Enable/Disable DLR events
  lib/glific/providers/gupshup/partner/partner_api.ex
  test/glific/partners/partners_test.exs
Labels: enhancement

#3698 Gupshup: Transfer Balance
  lib/glific/providers/gupshup/partner/partner_api.ex
  test/glific/partners/partners_test.exs
Labels: enhancement

#3736 WA Groups: Syncing tables to BQ
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: enhancement

#3740 Roles: Omit Glific Admin
  lib/glific.ex
  lib/glific/misc/flags.ex
  lib/glific/seeds/seeds_dev.ex
  test/glific/access_control_test.exs
  test/glific_web/schema/role_test.exs
Labels: bug

#3749 OpenAI: Run timeout
  lib/glific/third_party/openAI/chatGPT.ex
Labels: enhancement

#3746 Onboarding: Replaced custom password generator with library
  lib/glific/misc/password.ex
  lib/glific/saas/onboard.ex
  mix.exs
  mix.lock
  test/glific/password_text.exs
Labels: enhancement

#3750 OpenAI: Checking Assistant
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/openAI/chatGPT.ex
  test/glific/third_party/openAI/chatGPT_test.exs
Labels: enhancement

#3751 Bhasini: NMT TTS language check
  lib/glific/clients/common_webhook.ex
Labels: bug

#3752 GPTVision: Validating URL
  lib/glific/clients/common_webhook.ex
Labels: enhancement

#3753 GPTVision: Webhook Error
  lib/glific/clients/common_webhook.ex
  lib/glific/flows/webhook.ex
Labels: enhancement

#3739 Template flow: keyword triggering the flow after copy
  lib/glific/flows.ex
  test/glific/flows_test.exs
Labels: bug

#3759 OpenAI: Handling webhook errors
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/openAI/chatGPT.ex
Labels: enhancement

#3666 Contact Import Automation
  assets/gql/contacts/move.gql
  assets/gql/contacts/upload_report.gql
  config/config.exs
  lib/glific/contacts/import.ex
  lib/glific/contacts/import_worker.ex
  lib/glific/jobs/minute_worker.ex
  lib/glific/jobs/user_job_worker.ex
  lib/glific/jobs/user_jobs.ex
  lib/glific_web/resolvers/contacts.ex
  lib/glific_web/schema/contact_types.ex
  priv/repo/migrations/20240704090400_create_user_jobs.exs
  test/glific/contacts_test.exs
  test/glific/user_jobs_test.exs
  test/glific_web/schema/contact_test.exs
Labels: enhancement

#3683 Auto translate: handle the translation of contact variables
  lib/glific/third_party/google_translate/translate.ex
  test/glific/flows/translate/google_translate_test.exs
Labels: ready for review

#3766 Contact import: Added empty name and language validations
  lib/glific/contacts/import.ex
  lib/glific/contacts/import_worker.ex
  test/glific/contacts_test.exs
  test/glific_web/schema/contact_test.exs
Labels: ready for review

#3754 Webhook: Preventing webhook node execution if there is message stream
  lib/glific/flows/action.ex
  lib/glific/flows/webhook.ex
  test/glific/flows/action_test.exs
Labels: ready for review

#3758 OpenAI: English TTS
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/openAI/chatGPT.ex
Labels: bug

#3715 Flows: Floweditor enhancements
  lib/glific/flows.ex
  test/glific_web/flows/flow_editor_controller_test.exs
Labels: enhancement

#3779 Bhasini: Text to Speech fixes
  lib/glific/third_party/asr/bhasini.ex
  lib/glific/third_party/bhasini/bhasini.ex
  lib/glific/third_party/openAI/chatGPT.ex
Labels: bug
