Repository glific/glific, pull requests merged in 2024-03, with the labels that each got.

#3398 WA Group: Start Flow
  assets/gql/flows/wa_group_flow.gql
  lib/glific/flows.ex
  lib/glific/flows/action.ex
  lib/glific/flows/broadcast.ex
  lib/glific/flows/contact_action.ex
  lib/glific/flows/flow_context.ex
  lib/glific/flows/localization.ex
  lib/glific/flows/node.ex
  lib/glific/flows/wa_group_action.ex
  lib/glific/groups/wa_groups.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific_web/resolvers/flows.ex
  lib/glific_web/schema/flow_types.ex
  priv/data/flows/wa_group.json
  priv/repo/migrations/20240220134922_add_wa_group_id_to_flow_context.exs
  test/glific/flows/flow_context_test.exs
  test/glific_web/schema/flow_test.exs
  test/glific_web/schema/ticket_test.exs
Labels: enhancement

#3399 WA groups: Syncing group members
  assets/gql/contact_wa_groups/create.gql
  assets/gql/contact_wa_groups/fields.frag.gql
  assets/gql/contact_wa_groups/list.gql
  assets/gql/contact_wa_groups/sync.gql
  assets/gql/contact_wa_groups/update_wa_group.gql
  lib/glific/contacts/contact.ex
  lib/glific/groups/contact_wa_group.ex
  lib/glific/groups/contact_wa_groups.ex
  lib/glific/groups/wa_group.ex
  lib/glific/groups/wa_groups.ex
  lib/glific/jobs/minute_worker.ex
  lib/glific/providers/maytapi/wa_worker.ex
  lib/glific_web/resolvers/wa_group.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/contact_types.ex
  lib/glific_web/schema/contact_wa_group_types.ex
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  test/glific_web/schema/contact_wa_group_test.exs
  test/support/fixtures.ex
Labels: ready for review

#3415 WA groups: count API to get the count of wa group contacts
  assets/gql/contact_wa_groups/count_wa_contacts.gql
  lib/glific/groups/contact_wa_groups.ex
  lib/glific_web/resolvers/wa_group.ex
  lib/glific_web/schema/contact_wa_group_types.ex
  test/glific_web/schema/contact_wa_group_test.exs
Labels: ready for review

#3410 WA Group: Trigger
  api.docs/bruno/glific_api/Triggers/Create trigger.bru
  lib/glific/flows.ex
  lib/glific/flows/broadcast.ex
  lib/glific/flows/flow_context.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific/triggers.ex
  lib/glific/triggers/trigger.ex
  lib/glific_web/schema/trigger_types.ex
  priv/repo/migrations/20240229113537_add_wa_group_id_to_trigger.exs
  test/glific/flows/flow_context_test.exs
  test/glific/triggers_test.exs
  test/support/fixtures.ex
Labels: ready for review

#3428 Auto translate: Logs
  lib/glific/communications.ex
  lib/glific/flows/translate/google_translate.ex
  lib/glific/flows/translate/open_ai.ex
  lib/glific/flows/translate/simple.ex
  lib/glific/flows/translate/translate.ex
  lib/glific/flows/translate/translate_log.ex
  lib/glific/third_party/google_translate/translate.ex
  lib/glific/third_party/openAI/chatGPT.ex
  priv/repo/migrations/20240308095004_create_auto_translation_logs.exs
  test/glific/flows/translate/google_translate_test.exs
  test/glific/flows/translate/open_ai_test.exs
Labels: enhancement

#3431 WA Groups: Excluding DMs from search api
  assets/gql/searches/wa_search_multi.gql
  assets/gql/triggers/fields.frag.gql
  assets/gql/triggers/list.gql
  lib/glific/providers/maytapi/message.ex
  lib/glific/seeds/seeds_dev.ex
  lib/glific/wa_conversations.ex
  lib/glific_web/providers/maytapi/controller/message_controller.ex
  lib/glific_web/schema/message_types.ex
  lib/glific_web/schema/trigger_types.ex
  test/glific/groups/whatsapp_message_test.exs
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
  test/glific_web/schema/trigger_test.exs
  test/glific_web/schema/wa_search_test.exs
Labels: ready for review

#3432 WA groups: sync data to bigquery
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific/wa_group/wa_message.ex
Labels: ready for review

#3436 WA Group: Sending message to collection
  lib/glific/communications/wa_group_message.ex
  lib/glific/groups/wa_groups_collections.ex
  lib/glific/providers/maytapi/message.ex
  lib/glific/wa_group/wa_message.ex
  lib/glific_web/providers/maytapi/controller/message_controller.ex
  lib/glific_web/resolvers/messages.ex
  lib/glific_web/schema/message_types.ex
  priv/repo/migrations/20240117234740_add_wa_groups.exs
  test/glific/groups/whatsapp_message_test.exs
Labels: enhancement

#3439 Searches: Appending entity id
  lib/glific/searches.ex
  lib/glific_web/schema/search_type.ex
Labels: enhancement

#3412 test: fixing flaky test
  lib/glific/seeds/seeds_dev.ex
  test/glific_web/schema/ticket_test.exs
  test/glific_web/schema/wa_search_test.exs
Labels: ready for review

#3445 Enhancement: WA Search
  lib/glific/providers/maytapi/message.ex
  lib/glific/searches.ex
Labels: enhancement

#3433 Bugfix/fix apis
  lib/glific/contacts.ex
  lib/glific/conversations/wa_conversation.ex
  lib/glific/conversations_group.ex
  lib/glific/groups.ex
  lib/glific/searches.ex
  lib/glific/wa_messages.ex
  lib/glific_web/schema/contact_types.ex
  lib/glific_web/schema/contact_wa_group_types.ex
  test/glific/conversations_group_test.exs
  test/glific/groups_test.exs
  test/glific_web/schema/contact_test.exs
  test/support/fixtures.ex
Labels: ready for review

#3450 WA Search: Added label as filter
  lib/glific_web/resolvers/groups.ex
  lib/glific_web/resolvers/wa_group.ex
  lib/glific_web/schema/wa_group_types.ex
Labels: enhancement

#3435 Update bsp_status from the maytapi webhook after sending message
  lib/glific/communications/wa_group_message.ex
  lib/glific_web/providers/maytapi/controller/message_event_controller.ex
  lib/glific_web/providers/maytapi/shunt.ex
  test/glific_web/schema/wa_message_test.exs
Labels: ready for review

#3448 WA Groups: Remove participants from Whatsapp group
  lib/glific/groups/contact_wa_groups.ex
  lib/glific/groups/wa_groups.ex
  lib/glific/providers/maytapi/api_client.ex
  lib/glific_web/resolvers/wa_group.ex
  test/glific_web/schema/contact_wa_group_test.exs
Labels: ready for review

#3453 Tickets: consistent csv header and content ordering
  lib/glific/tickets.ex
Labels: ready for review

#3460 WA Groups: sending caption with media message
  lib/glific/providers/maytapi/wa_messages.ex
Labels: ready for review

#3464 WA Group: Hotfix for media with caption
  lib/glific/providers/maytapi/wa_messages.ex
  test/glific_web/schema/wa_message_test.exs
  test/support/fixtures.ex
Labels: bug

#3466 WA Group: Clean Callbacks on adding credentials
  lib/glific/groups/wa_groups.ex
  lib/glific/partners.ex
  lib/glific/providers/maytapi/response_handler.ex
  lib/glific/wa_managed_phones.ex
  lib/glific_web/schema/message_types.ex
  test/glific/groups/whatsapp_group_test.exs
  test/glific/partners/partners_test.exs
  test/glific/wa_managed_phones_test.exs
Labels: bug

#3467 WA Groups: Group API
  assets/gql/wa_group_collection/count.gql
  assets/gql/wa_groups/by_id.gql
  assets/gql/wa_groups/count.gql
  lib/glific_web/resolvers/wa_group.ex
  lib/glific_web/schema/group_types.ex
  lib/glific_web/schema/wa_group_types.ex
  test/glific_web/schema/wa_group_test.exs
Labels: enhancement

#3469 WA Group: Creating notification on error message
  lib/glific/providers/maytapi/response_handler.ex
Labels: enhancement
