Repository glific/glific, pull requests merged in 2025-03, with the labels that each got.

#4050 Added Gupshup pending migrations from `/sm` endpoint
  lib/glific/partners.ex
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific/providers/gupshup/wallet.ex
  lib/glific_web/resolvers/contacts.ex
  priv/gettext/errors.pot
  test/glific/partners/partners_test.exs
  test/glific_web/schema/contact_test.exs
  test/glific_web/schema/provider_test.exs
Labels: Priority: High

#4055 Custom certificates: certificate template APIs
  assets/gql/certificates/by_id.gql
  assets/gql/certificates/count.gql
  assets/gql/certificates/create.gql
  assets/gql/certificates/delete.gql
  assets/gql/certificates/fields.frag.gql
  assets/gql/certificates/list.gql
  assets/gql/certificates/update.gql
  lib/glific/certificates/certificate.ex
  lib/glific/certificates/certificate_template.ex
  lib/glific/enums/constants/enums.ex
  lib/glific/enums/ecto_enums.ex
  lib/glific/enums/enums.ex
  lib/glific_web/resolvers/certificate.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/certificate_types.ex
  lib/glific_web/schema/enum_types.ex
  priv/repo/migrations/20250227212728_certificate_templates.exs
  test/glific_web/schema/certificate_test.exs
Labels: ready for review

#4065 Flows: Able to run wa group flows even if gupshup credentials are inactive
  lib/glific/flows/broadcast.ex
  test/glific_web/schema/flow_test.exs
Labels: Priority: High, bug

#4056 Custom certificate: webhook function to generate certificate
  .github/workflows/continuous-integration.yml
  config/dev.exs
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/google_slide/slide.ex
  priv/repo/seeds/20250312192850_add_google_slides_provider.exs
  test/glific/flows/common_webhook_test.exs
Labels: ready for review, Priority: High

#4057 Wa groups: notification msg for start flow for collections
  lib/glific/flows/broadcast.ex
  lib/glific/providers/maytapi/message.ex
  test/glific/groups/whatsapp_message_test.exs
Labels: Priority: Medium

#4074 WA Messages: Checking maytapi provider is active instead of Gupshup
  lib/glific/providers/maytapi/wa_worker.ex
  test/glific/groups/whatsapp_message_test.exs
Labels: Priority: High

#4067 Custom certificates: managing certificates issued to contacts
  assets/gql/organizations/get_services.gql
  config/dev.exs
  lib/glific.ex
  lib/glific/certificates/certificate.ex
  lib/glific/certificates/certificate_template.ex
  lib/glific/certificates/issued_certificate.ex
  lib/glific/clients/common_webhook.ex
  lib/glific/misc/flags.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific/third_party/google_slide/slide.ex
  lib/glific_web/schema/organization_types.ex
  mix.exs
  mix.lock
  priv/repo/migrations/20250227212728_certificate_templates.exs
  test/glific/flows/common_webhook_test.exs
  test/glific_web/schema/certificate_test.exs
  test/glific_web/schema/organization_test.exs
Labels: Priority: High

#4088 Flaky test: Fix inactive opt-in flaky test case
  test/glific/processor/consumer_flow_test.exs
Labels: Priority: High
