Repository glific/glific, pull requests merged in 2025-02, with the labels that each got.

#4003 Gupshup: Removed optin api dependency
  lib/glific/application.ex
  lib/glific/contacts/import.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific_web/controllers/api/v1/registration_controller.ex
  test/glific_web/registration_controller_test.exs
  test/glific_web/schema/contact_test.exs
Labels: ready for review

#4015 Legacy Code: Cleanup stale providers
  assets/gql/organizations/get_services.gql
  assets/scripts/db_filter_org.exs
  coveralls.json
  lib/glific/clients/bandhu.ex
  lib/glific/clients/common_webhook.ex
  lib/glific/misc/flags.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific/third_party/llm4dev/llm4dev.ex
  lib/glific_web/resolvers/llm4dev.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/llm4dev_types.ex
  lib/glific_web/schema/organization_types.ex
  priv/gettext/errors.pot
  priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs
  test/glific_web/schema/organization_test.exs
Labels: enhancement

#4011 OpenAI: Remove citation
  lib/glific/third_party/openAI/chatGPT.ex
  test/glific/third_party/openAI/chatGPT_test.exs
Labels: enhancement

#4013 BQ: Fixes for syncing speed sends
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
Labels: bug

#3988 Contacts: Don't update the existing contact language.
  lib/glific/contacts/import.ex
  test/glific/contacts_test.exs
Labels: ready for review

#3993 WA Groups: Webhook function for sending polls in flow
  lib/glific/clients/common_webhook.ex
  lib/glific/flows.ex
  lib/glific/flows/action.ex
  lib/glific/flows/exit.ex
  lib/glific/flows/flow_context.ex
  lib/glific/flows/webhook.ex
  lib/glific/flows/webhook_log.ex
  lib/glific/wa_poll.ex
  lib/glific_web/providers/maytapi/controller/message_event_controller.ex
  priv/gettext/errors.pot
  priv/repo/migrations/20250106161903_wa_polls.exs
  test/glific/flows/common_webhook_test.exs
  test/glific/flows/flow_context_test.exs
  test/glific/flows/webhook_test.exs
  test/glific_web/schema/wa_reaction_test.exs
Labels: ready for review

#4034 WA Groups: Added Poll metrics
  lib/glific/clients/common_webhook.ex
  lib/glific/communications/wa_group_message.ex
  lib/glific/providers/maytapi/message.ex
  lib/glific/providers/maytapi/wa_messages.ex
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific/wa_group/wa_message.ex
  lib/glific/wa_group/wa_poll.ex
  lib/glific/wa_group/wa_reaction.ex
  lib/glific/wa_poll.ex
  lib/glific_web/resolvers/wa_poll.ex
  test/glific_web/schema/wa_poll_test.exs
  test/support/fixtures.ex
Labels: ready for review

#4041 Legacy Code: Cleanup Chatbase
  TODO.md
  priv/gettext/en/LC_MESSAGES/errors.po
  priv/gettext/errors.pot
  priv/gettext/hi/LC_MESSAGES/errors.po
Labels: enhancement

#4019 Webhook: Easy manage 3rd party services
  lib/glific/clients/common_webhook.ex
  lib/glific_web/flows/flow_resume_controller.ex
  lib/glific_web/router.ex
  priv/data/flows/wait_for_result.json
  test/glific_web/flows/flow_resume_controller_test.exs
Labels: enhancement
