Repository glific/glific, pull requests merged in 2025-05, with the labels that each got.

#4126 disabled internal dashboard mails
  lib/glific/jobs/minute_worker.ex
Labels: Priority: Low

#4115 Template: Fix sync api for large no. of templates
  lib/glific/templates.ex
  lib/glific/templates/template_worker.ex
  lib/glific_web/resolvers/templates.ex
  test/glific/templates_test.exs
  test/glific_web/schema/session_template_test.exs
Labels: Priority: Medium

#4133 Fix bulk applying templates with buttons failing
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific/providers/gupshup/template.ex
  lib/glific/templates/template_worker.ex
  mix.exs
  mix.lock
  test/glific/templates_test.exs
Labels: ready for review, bug

#4106 Add language change logs in contact_history table
  lib/glific/contacts/import.ex
  test/glific/contacts_test.exs
Labels: Priority: Medium

#4166 BQ: Update table_id for simulator contacts in BQ jobs table
  lib/glific/third_party/bigquery/bigquery_worker.ex
  test/glific/bigquery_test.exs
Labels: ready for review, bug

#4175 [4145] Fix null message for message reactions
  lib/glific_web/providers/gupshup/controllers/billing_event_controller.ex
  lib/glific_web/providers/gupshup/controllers/default_controller.ex
  lib/glific_web/providers/gupshup/controllers/message_controller.ex
  lib/glific_web/providers/gupshup/controllers/message_event_controller.ex
  lib/glific_web/providers/gupshup/controllers/user_event_controller.ex
  test/glific_web/providers/gupshup/controllers/billing_event_controller_test.exs
  test/glific_web/providers/gupshup/controllers/default_controller_test.exs
  test/glific_web/providers/gupshup/controllers/message_controller_test.exs
  test/glific_web/providers/gupshup/controllers/message_event_controller_test.exs
  test/glific_web/providers/gupshup/controllers/user_event_controller_test.exs
  test/glific_web/providers/maytapi/controllers/message_controller_test.exs
Labels: bug

#4177 Gupshup: Removed using deprecated /user api
  lib/glific/partners.ex
  lib/glific/providers/contact_behaviour.ex
  lib/glific/providers/gupshup/api_client.ex
  lib/glific/providers/gupshup/contacts.ex
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific/providers/gupshup_enterprise/contacts.ex
  lib/glific/saas/queries.ex
  lib/glific/seeds/seeds_optins.ex
  priv/gettext/error.pot
  priv/gettext/errors.pot
  test/glific/flows/contact_action_test.exs
  test/glific/partners/onboard_test.exs
  test/glific/partners/partners_test.exs
Labels: P1

#4178 Bhasini: Removed processors from tts
  lib/glific/clients/sarc.ex
  lib/glific/third_party/bhasini/bhasini.ex
  test/glific/clients_test.exs
Labels: P0

#4183 [4145] Send empty body for Gupshup callbacks
  lib/glific_web/providers/gupshup/controllers/billing_event_controller.ex
  lib/glific_web/providers/gupshup/controllers/default_controller.ex
  lib/glific_web/providers/gupshup/controllers/message_event_controller.ex
  lib/glific_web/providers/gupshup/controllers/user_event_controller.ex
  test/glific_web/providers/gupshup/controllers/billing_event_controller_test.exs
  test/glific_web/providers/gupshup/controllers/default_controller_test.exs
  test/glific_web/providers/gupshup/controllers/message_controller_test.exs
  test/glific_web/providers/gupshup/controllers/message_event_controller_test.exs
  test/glific_web/providers/gupshup/controllers/user_event_controller_test.exs
Labels: bug
