Repository glific/glific, pull requests merged in 2025-04, with the labels that each got.

#4093 Custom certificates: Deleting template copy and slide url validations
  lib/glific/certificates/certificate.ex
  lib/glific/certificates/certificate_template.ex
  lib/glific/clients/common_webhook.ex
  lib/glific/third_party/google_slide/slide.ex
  test/glific/flows/common_webhook_test.exs
  test/glific_web/schema/certificate_test.exs
Labels: Priority: High

#4094 AI Platform: using updated format
  lib/glific_web/flows/flow_resume_controller.ex
  test/glific_web/flows/flow_resume_controller_test.exs
Labels: enhancement

#4091 Added url preview support for text messages
  lib/glific/providers/gupshup/message.ex
Labels: Priority: High

#4090 Bigquery: Handling date-only format in the formatter
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific_web/providers/maytapi/controller/message_event_controller.ex
  test/glific/bigquery_test.exs
  test/glific_web/schema/wa_reaction_test.exs
Labels: Priority: High

#4105 Template: Update the get template api end point
  lib/glific/providers/gupshup/api_client.ex
  lib/glific/providers/gupshup/partner/partner_api.ex
  lib/glific/providers/gupshup/template.ex
  priv/gettext/errors.pot
  test/glific/partners/partners_test.exs
Labels: ready for review, Priority: High

#4102 Flow: add skip validation field in flow
  lib/glific/flows/flow.ex
  lib/glific_web/schema/flow_types.ex
  priv/repo/migrations/20250405133306_skip_validation field in flows.exs
  test/glific/flows_test.exs
Labels: ready for review, Priority: High

#4098 WA Groups: Handling translation for case handlers in split_by_expression node
  lib/glific/flows/localization.ex
  test/glific/flows/action_test.exs
  test/glific/flows/flow_context_test.exs
  test/glific/flows/router_test.exs
  test/support/fixtures.ex
Labels: Priority: High

#4064 Custom certificates
  assets/gql/certificates/by_id.gql
  assets/gql/certificates/count.gql
  assets/gql/certificates/create.gql
  assets/gql/certificates/delete.gql
  assets/gql/certificates/fields.frag.gql
  assets/gql/certificates/list.gql
  assets/gql/certificates/update.gql
  assets/gql/organizations/get_services.gql
  lib/glific.ex
  lib/glific/certificates/certificate.ex
  lib/glific/certificates/certificate_template.ex
  lib/glific/certificates/issued_certificate.ex
  lib/glific/clients/common_webhook.ex
  lib/glific/enums/constants/enums.ex
  lib/glific/enums/ecto_enums.ex
  lib/glific/enums/enums.ex
  lib/glific/misc/flags.ex
  lib/glific/partners.ex
  lib/glific/partners/organization.ex
  lib/glific/third_party/bigquery/bigquery.ex
  lib/glific/third_party/bigquery/bigquery_schema.ex
  lib/glific/third_party/bigquery/bigquery_worker.ex
  lib/glific/third_party/google_slide/slide.ex
  lib/glific_web/resolvers/certificate.ex
  lib/glific_web/schema.ex
  lib/glific_web/schema/certificate_types.ex
  lib/glific_web/schema/enum_types.ex
  lib/glific_web/schema/organization_types.ex
  mix.exs
  mix.lock
  priv/gettext/errors.pot
  priv/repo/migrations/20250227212728_certificate_templates.exs
  priv/repo/seeds/20250312192850_add_google_slides_provider.exs
  test/glific/clients_test.exs
  test/glific/flows/common_webhook_test.exs
  test/glific_web/schema/certificate_test.exs
  test/glific_web/schema/organization_test.exs
Labels: Priority: High

#4103 Webhook: Support headers
  lib/glific/clients.ex
  lib/glific/clients/common_webhook.ex
  lib/glific/flows/webhook.ex
Labels: enhancement, Priority: Medium

#4046 Webhook: Handle empty GET body
  lib/glific/flows/webhook.ex
  test/glific/flows/webhook_test.exs
Labels: Priority: Medium, bug

#4123 fix: 🐛 Fix organization_id access in error logging
  lib/glific/providers/gupshup/response_handler.ex
  test/glific/communications_test.exs
Labels: Priority: Low, bug

#4120 Custom certificates: Added metric, erasing older issued_certificates weekly
  lib/glific/certificates/certificate.ex
  lib/glific/erase.ex
Labels: Priority: Medium

#4028 Wa groups: Fix deletion taking long time when syncing
  lib/glific/partners.ex
  lib/glific/providers/maytapi/api_client.ex
  lib/glific/providers/maytapi/wa_worker.ex
  lib/glific/wa_managed_phones.ex
  priv/gettext/errors.pot
  test/glific/partners/partners_test.exs
  test/glific/wa_managed_phones_test.exs
Labels: Priority: High, ops

#4111 GCS: Media url sync enhancements
  lib/glific/communications/mailer.ex
  lib/glific/jobs/minute_worker.ex
  lib/glific/mails/media_sync_mail.ex
  lib/glific/messages/message_media.ex
  lib/glific/third_party/gcs/gcs.ex
  lib/glific/third_party/gcs/gcs_worker.ex
  priv/repo/migrations/20250407174642_add_error_message_media.exs
  test/glific/gcs_worker_test.exs
Labels: Priority: High
